/*

+-----------------------------------------------------------------+
|     Created by Chirag Mehta - http://chir.ag/projects/ntc       |
|-----------------------------------------------------------------|
|               ntc js (Name that Color JavaScript)               |
+-----------------------------------------------------------------+

All the functions, code, lists etc. have been written specifically
for the Name that Color JavaScript by Chirag Mehta unless otherwise
specified.

This script is released under the: Creative Commons License:
Attribution 2.5 http://creativecommons.org/licenses/by/2.5/

Sample Usage:

  <script type="text/javascript" src="ntc.js"></script>

  <script type="text/javascript">

    var n_match  = ntc.name("#6195ED");
    n_rgb        = n_match[0]; // This is the RGB value of the closest matching color
    n_name       = n_match[1]; // This is the text string for the name of the match
    n_exactmatch = n_match[2]; // True if exact color match, False if close-match

    alert(n_match);

  </script>

*/

var ntc = {

  init: function() {
    var color, rgb, hsl;
    for(var i = 0; i < ntc.names.length; i++)
    {
      color = "#" + ntc.names[i][0];
      rgb = ntc.rgb(color);
      hsl = ntc.hsl(color);
      ntc.names[i].push(rgb[0], rgb[1], rgb[2], hsl[0], hsl[1], hsl[2]);
    }
  },

  name: function(color) {

    color = color.toUpperCase();
    if(color.length < 3 || color.length > 7)
      return ["#000000", "Invalid Color: " + color, false];
    if(color.length % 3 == 0)
      color = "#" + color;
    if(color.length == 4)
      color = "#" + color.substr(1, 1) + color.substr(1, 1) + color.substr(2, 1) + color.substr(2, 1) + color.substr(3, 1) + color.substr(3, 1);

    var rgb = ntc.rgb(color);
    var r = rgb[0], g = rgb[1], b = rgb[2];
    var hsl = ntc.hsl(color);
    var h = hsl[0], s = hsl[1], l = hsl[2];
    var ndf1 = 0; ndf2 = 0; ndf = 0;
    var cl = -1, df = -1;

    for(var i = 0; i < ntc.names.length; i++)
    {
      if(color == "#" + ntc.names[i][0])
        return ["#" + ntc.names[i][0], ntc.names[i][1], true];

      ndf1 = Math.pow(r - ntc.names[i][2], 2) + Math.pow(g - ntc.names[i][3], 2) + Math.pow(b - ntc.names[i][4], 2);
      ndf2 = Math.pow(h - ntc.names[i][5], 2) + Math.pow(s - ntc.names[i][6], 2) + Math.pow(l - ntc.names[i][7], 2);
      ndf = ndf1 + ndf2 * 2;
      if(df < 0 || df > ndf)
      {
        df = ndf;
        cl = i;
      }
    }

    return (cl < 0 ? ["#000000", "Invalid Color: " + color, false] : ["#" + ntc.names[cl][0], ntc.names[cl][1], false]);
  },
  
  wiki: function(color) {

    color = color.toUpperCase();
    if(color.length < 3 || color.length > 7)
      return ["#000000", "Invalid Color: " + color, false];
    if(color.length % 3 == 0)
      color = "#" + color;
    if(color.length == 4)
      color = "#" + color.substr(1, 1) + color.substr(1, 1) + color.substr(2, 1) + color.substr(2, 1) + color.substr(3, 1) + color.substr(3, 1);

    var rgb = ntc.rgb(color);
    var r = rgb[0], g = rgb[1], b = rgb[2];
    var hsl = ntc.hsl(color);
    var h = hsl[0], s = hsl[1], l = hsl[2];
    var ndf1 = 0; ndf2 = 0; ndf = 0;
    var cl = -1, df = -1;

    for(var i = 0; i < ntc.wikis.length; i++)
    {
      if(color == "#" + ntc.wikis[i][0])
        return ["#" + ntc.wikis[i][0], ntc.wikis[i][1], true];

      ndf1 = Math.pow(r - ntc.wikis[i][2], 2) + Math.pow(g - ntc.wikis[i][3], 2) + Math.pow(b - ntc.wikis[i][4], 2);
      ndf2 = Math.pow(h - ntc.wikis[i][5], 2) + Math.pow(s - ntc.wikis[i][6], 2) + Math.pow(l - ntc.wikis[i][7], 2);
      ndf = ndf1 + ndf2 * 2;
      if(df < 0 || df > ndf)
      {
        df = ndf;
        cl = i;
      }
    }

    return (cl < 0 ? ["#000000", "Invalid Color: " + color, false] : ["#" + ntc.wikis[cl][0], ntc.wikis[cl][1], false]);
  },

  // adopted from: Farbtastic 1.2
  // http://acko.net/dev/farbtastic
  hsl: function (color) {

    var rgb = [parseInt('0x' + color.substring(1, 3)) / 255, parseInt('0x' + color.substring(3, 5)) / 255, parseInt('0x' + color.substring(5, 7)) / 255];
    var min, max, delta, h, s, l;
    var r = rgb[0], g = rgb[1], b = rgb[2];

    min = Math.min(r, Math.min(g, b));
    max = Math.max(r, Math.max(g, b));
    delta = max - min;
    l = (min + max) / 2;

    s = 0;
    if(l > 0 && l < 1)
      s = delta / (l < 0.5 ? (2 * l) : (2 - 2 * l));

    h = 0;
    if(delta > 0)
    {
      if (max == r && max != g) h += (g - b) / delta;
      if (max == g && max != b) h += (2 + (b - r) / delta);
      if (max == b && max != r) h += (4 + (r - g) / delta);
      h /= 6;
    }
    return [parseInt(h * 255), parseInt(s * 255), parseInt(l * 255)];
  },

  // adopted from: Farbtastic 1.2
  // http://acko.net/dev/farbtastic
  rgb: function(color) {
    return [parseInt('0x' + color.substring(1, 3)), parseInt('0x' + color.substring(3, 5)),  parseInt('0x' + color.substring(5, 7))];
  },

  names: [
["000000", "Black"],
["000080", "Navy Blue"],
["0000C8", "Dark Blue"],
["0000FF", "Blue"],
["000741", "Stratos"],
["001B1C", "Swamp"],
["002387", "Resolution Blue"],
["002900", "Deep Fir"],
["002E20", "Burnham"],
["002FA7", "International Klein Blue"],
["003153", "Prussian Blue"],
["003366", "Midnight Blue"],
["003399", "Smalt"],
["003532", "Deep Teal"],
["003E40", "Cyprus"],
["004620", "Kaitoke Green"],
["0047AB", "Cobalt"],
["004816", "Crusoe"],
["004950", "Sherpa Blue"],
["0056A7", "Endeavour"],
["00581A", "Camarone"],
["0066CC", "Science Blue"],
["0066FF", "Blue Ribbon"],
["00755E", "Tropical Rain Forest"],
["0076A3", "Allports"],
["007BA7", "Deep Cerulean"],
["007EC7", "Lochmara"],
["007FFF", "Azure Radiance"],
["008080", "Teal"],
["0095B6", "Bondi Blue"],
["009DC4", "Pacific Blue"],
["00A693", "Persian Green"],
["00A86B", "Jade"],
["00CC99", "Caribbean Green"],
["00CCCC", "Robin's Egg Blue"],
["00FF00", "Green"],
["00FF7F", "Spring Green"],
["00FFFF", "Cyan / Aqua"],
["010D1A", "Blue Charcoal"],
["011635", "Midnight"],
["011D13", "Holly"],
["012731", "Daintree"],
["01361C", "Cardin Green"],
["01371A", "County Green"],
["013E62", "Astronaut Blue"],
["013F6A", "Regal Blue"],
["014B43", "Aqua Deep"],
["015E85", "Orient"],
["016162", "Blue Stone"],
["016D39", "Fun Green"],
["01796F", "Pine Green"],
["017987", "Blue Lagoon"],
["01826B", "Deep Sea"],
["01A368", "Green Haze"],
["022D15", "English Holly"],
["02402C", "Sherwood Green"],
["02478E", "Congress Blue"],
["024E46", "Evening Sea"],
["026395", "Bahama Blue"],
["02866F", "Observatory"],
["02A4D3", "Cerulean"],
["03163C", "Tangaroa"],
["032B52", "Green Vogue"],
["036A6E", "Mosque"],
["041004", "Midnight Moss"],
["041322", "Black Pearl"],
["042E4C", "Blue Whale"],
["044022", "Zuccini"],
["044259", "Teal Blue"],
["051040", "Deep Cove"],
["051657", "Gulf Blue"],
["055989", "Venice Blue"],
["056F57", "Watercourse"],
["062A78", "Catalina Blue"],
["063537", "Tiber"],
["069B81", "Gossamer"],
["06A189", "Niagara"],
["073A50", "Tarawera"],
["080110", "Jaguar"],
["081910", "Black Bean"],
["082567", "Deep Sapphire"],
["088370", "Elf Green"],
["08E8DE", "Bright Turquoise"],
["092256", "Downriver"],
["09230F", "Palm Green"],
["09255D", "Madison"],
["093624", "Bottle Green"],
["095859", "Deep Sea Green"],
["097F4B", "Salem"],
["0A001C", "Black Russian"],
["0A480D", "Dark Fern"],
["0A6906", "Japanese Laurel"],
["0A6F75", "Atoll"],
["0B0B0B", "Cod Gray"],
["0B0F08", "Marshland"],
["0B1107", "Gordons Green"],
["0B1304", "Black Forest"],
["0B6207", "San Felix"],
["0BDA51", "Malachite"],
["0C0B1D", "Ebony"],
["0C0D0F", "Woodsmoke"],
["0C1911", "Racing Green"],
["0C7A79", "Surfie Green"],
["0C8990", "Blue Chill"],
["0D0332", "Black Rock"],
["0D1117", "Bunker"],
["0D1C19", "Aztec"],
["0D2E1C", "Bush"],
["0E0E18", "Cinder"],
["0E2A30", "Firefly"],
["0F2D9E", "Torea Bay"],
["10121D", "Vulcan"],
["101405", "Green Waterloo"],
["105852", "Eden"],
["110C6C", "Arapawa"],
["120A8F", "Ultramarine"],
["123447", "Elephant"],
["126B40", "Jewel"],
["130000", "Diesel"],
["130A06", "Asphalt"],
["13264D", "Blue Zodiac"],
["134F19", "Parsley"],
["140600", "Nero"],
["1450AA", "Tory Blue"],
["151F4C", "Bunting"],
["1560BD", "Denim"],
["15736B", "Genoa"],
["161928", "Mirage"],
["161D10", "Hunter Green"],
["162A40", "Big Stone"],
["163222", "Celtic"],
["16322C", "Timber Green"],
["163531", "Gable Green"],
["171F04", "Pine Tree"],
["175579", "Chathams Blue"],
["182D09", "Deep Forest Green"],
["18587A", "Blumine"],
["19330E", "Palm Leaf"],
["193751", "Nile Blue"],
["1959A8", "Fun Blue"],
["1A1A68", "Lucky Point"],
["1AB385", "Mountain Meadow"],
["1B0245", "Tolopea"],
["1B1035", "Haiti"],
["1B127B", "Deep Koamaru"],
["1B1404", "Acadia"],
["1B2F11", "Seaweed"],
["1B3162", "Biscay"],
["1B659D", "Matisse"],
["1C1208", "Crowshead"],
["1C1E13", "Rangoon Green"],
["1C39BB", "Persian Blue"],
["1C402E", "Everglade"],
["1C7C7D", "Elm"],
["1D6142", "Green Pea"],
["1E0F04", "Creole"],
["1E1609", "Karaka"],
["1E1708", "El Paso"],
["1E385B", "Cello"],
["1E433C", "Te Papa Green"],
["1E90FF", "Dodger Blue"],
["1E9AB0", "Eastern Blue"],
["1F120F", "Night Rider"],
["1FC2C2", "Java"],
["20208D", "Jacksons Purple"],
["202E54", "Cloud Burst"],
["204852", "Blue Dianne"],
["211A0E", "Eternity"],
["220878", "Deep Blue"],
["228B22", "Forest Green"],
["233418", "Mallard"],
["240A40", "Violet"],
["240C02", "Kilamanjaro"],
["242A1D", "Log Cabin"],
["242E16", "Black Olive"],
["24500F", "Green House"],
["251607", "Graphite"],
["251706", "Cannon Black"],
["251F4F", "Port Gore"],
["25272C", "Shark"],
["25311C", "Green Kelp"],
["2596D1", "Curious Blue"],
["260368", "Paua"],
["26056A", "Paris M"],
["261105", "Wood Bark"],
["261414", "Gondola"],
["262335", "Steel Gray"],
["26283B", "Ebony Clay"],
["273A81", "Bay of Many"],
["27504B", "Plantation"],
["278A5B", "Eucalyptus"],
["281E15", "Oil"],
["283A77", "Astronaut"],
["286ACD", "Mariner"],
["290C5E", "Violent Violet"],
["292130", "Bastille"],
["292319", "Zeus"],
["292937", "Charade"],
["297B9A", "Jelly Bean"],
["29AB87", "Jungle Green"],
["2A0359", "Cherry Pie"],
["2A140E", "Coffee Bean"],
["2A2630", "Baltic Sea"],
["2A380B", "Turtle Green"],
["2A52BE", "Cerulean Blue"],
["2B0202", "Sepia Black"],
["2B194F", "Valhalla"],
["2B3228", "Heavy Metal"],
["2C0E8C", "Blue Gem"],
["2C1632", "Revolver"],
["2C2133", "Bleached Cedar"],
["2C8C84", "Lochinvar"],
["2D2510", "Mikado"],
["2D383A", "Outer Space"],
["2D569B", "St Tropaz"],
["2E0329", "Jacaranda"],
["2E1905", "Jacko Bean"],
["2E3222", "Rangitoto"],
["2E3F62", "Rhino"],
["2E8B57", "Sea Green"],
["2EBFD4", "Scooter"],
["2F270E", "Onion"],
["2F3CB3", "Governor Bay"],
["2F519E", "Sapphire"],
["2F5A57", "Spectra"],
["2F6168", "Casal"],
["300529", "Melanzane"],
["301F1E", "Cocoa Brown"],
["302A0F", "Woodrush"],
["304B6A", "San Juan"],
["30D5C8", "Turquoise"],
["311C17", "Eclipse"],
["314459", "Pickled Bluewood"],
["315BA1", "Azure"],
["31728D", "Calypso"],
["317D82", "Paradiso"],
["32127A", "Persian Indigo"],
["32293A", "Blackcurrant"],
["323232", "Mine Shaft"],
["325D52", "Stromboli"],
["327C14", "Bilbao"],
["327DA0", "Astral"],
["33036B", "Christalle"],
["33292F", "Thunder"],
["33CC99", "Shamrock"],
["341515", "Tamarind"],
["350036", "Mardi Gras"],
["350E42", "Valentino"],
["350E57", "Jagger"],
["353542", "Tuna"],
["354E8C", "Chambray"],
["363050", "Martinique"],
["363534", "Tuatara"],
["363C0D", "Waiouru"],
["36747D", "Ming"],
["368716", "La Palma"],
["370202", "Chocolate"],
["371D09", "Clinker"],
["37290E", "Brown Tumbleweed"],
["373021", "Birch"],
["377475", "Oracle"],
["380474", "Blue Diamond"],
["381A51", "Grape"],
["383533", "Dune"],
["384555", "Oxford Blue"],
["384910", "Clover"],
["394851", "Limed Spruce"],
["396413", "Dell"],
["3A0020", "Toledo"],
["3A2010", "Sambuca"],
["3A2A6A", "Jacarta"],
["3A686C", "William"],
["3A6A47", "Killarney"],
["3AB09E", "Keppel"],
["3B000B", "Temptress"],
["3B0910", "Aubergine"],
["3B1F1F", "Jon"],
["3B2820", "Treehouse"],
["3B7A57", "Amazon"],
["3B91B4", "Boston Blue"],
["3C0878", "Windsor"],
["3C1206", "Rebel"],
["3C1F76", "Meteorite"],
["3C2005", "Dark Ebony"],
["3C3910", "Camouflage"],
["3C4151", "Bright Gray"],
["3C4443", "Cape Cod"],
["3C493A", "Lunar Green"],
["3D0C02", "Bean  "],
["3D2B1F", "Bistre"],
["3D7D52", "Goblin"],
["3E0480", "Kingfisher Daisy"],
["3E1C14", "Cedar"],
["3E2B23", "English Walnut"],
["3E2C1C", "Black Marlin"],
["3E3A44", "Ship Gray"],
["3EABBF", "Pelorous"],
["3F2109", "Bronze"],
["3F2500", "Cola"],
["3F3002", "Madras"],
["3F307F", "Minsk"],
["3F4C3A", "Cabbage Pont"],
["3F583B", "Tom Thumb"],
["3F5D53", "Mineral Green"],
["3FC1AA", "Puerto Rico"],
["3FFF00", "Harlequin"],
["401801", "Brown Pod"],
["40291D", "Cork"],
["403B38", "Masala"],
["403D19", "Thatch Green"],
["405169", "Fiord"],
["40826D", "Viridian"],
["40A860", "Chateau Green"],
["410056", "Ripe Plum"],
["411F10", "Paco"],
["412010", "Deep Oak"],
["413C37", "Merlin"],
["414257", "Gun Powder"],
["414C7D", "East Bay"],
["4169E1", "Royal Blue"],
["41AA78", "Ocean Green"],
["420303", "Burnt Maroon"],
["423921", "Lisbon Brown"],
["427977", "Faded Jade"],
["431560", "Scarlet Gum"],
["433120", "Iroko"],
["433E37", "Armadillo"],
["434C59", "River Bed"],
["436A0D", "Green Leaf"],
["44012D", "Barossa"],
["441D00", "Morocco Brown"],
["444954", "Mako"],
["454936", "Kelp"],
["456CAC", "San Marino"],
["45B1E8", "Picton Blue"],
["460B41", "Loulou"],
["462425", "Crater Brown"],
["465945", "Gray Asparagus"],
["4682B4", "Steel Blue"],
["480404", "Rustic Red"],
["480607", "Bulgarian Rose"],
["480656", "Clairvoyant"],
["481C1C", "Cocoa Bean"],
["483131", "Woody Brown"],
["483C32", "Taupe"],
["49170C", "Van Cleef"],
["492615", "Brown Derby"],
["49371B", "Metallic Bronze"],
["495400", "Verdun Green"],
["496679", "Blue Bayoux"],
["497183", "Bismark"],
["4A2A04", "Bracken"],
["4A3004", "Deep Bronze"],
["4A3C30", "Mondo"],
["4A4244", "Tundora"],
["4A444B", "Gravel"],
["4A4E5A", "Trout"],
["4B0082", "Pigment Indigo"],
["4B5D52", "Nandor"],
["4C3024", "Saddle"],
["4C4F56", "Abbey"],
["4D0135", "Blackberry"],
["4D0A18", "Cab Sav"],
["4D1E01", "Indian Tan"],
["4D282D", "Cowboy"],
["4D282E", "Livid Brown"],
["4D3833", "Rock"],
["4D3D14", "Punga"],
["4D400F", "Bronzetone"],
["4D5328", "Woodland"],
["4E0606", "Mahogany"],
["4E2A5A", "Bossanova"],
["4E3B41", "Matterhorn"],
["4E420C", "Bronze Olive"],
["4E4562", "Mulled Wine"],
["4E6649", "Axolotl"],
["4E7F9E", "Wedgewood"],
["4EABD1", "Shakespeare"],
["4F1C70", "Honey Flower"],
["4F2398", "Daisy Bush"],
["4F69C6", "Indigo"],
["4F7942", "Fern Green"],
["4F9D5D", "Fruit Salad"],
["4FA83D", "Apple"],
["504351", "Mortar"],
["507096", "Kashmir Blue"],
["507672", "Cutty Sark"],
["50C878", "Emerald"],
["514649", "Emperor"],
["516E3D", "Chalet Green"],
["517C66", "Como"],
["51808F", "Smalt Blue"],
["52001F", "Castro"],
["520C17", "Maroon Oak"],
["523C94", "Gigas"],
["533455", "Voodoo"],
["534491", "Victoria"],
["53824B", "Hippie Green"],
["541012", "Heath"],
["544333", "Judge Gray"],
["54534D", "Fuscous Gray"],
["549019", "Vida Loca"],
["55280C", "Cioccolato"],
["555B10", "Saratoga"],
["556D56", "Finlandia"],
["5590D9", "Havelock Blue"],
["56B4BE", "Fountain Blue"],
["578363", "Spring Leaves"],
["583401", "Saddle Brown"],
["585562", "Scarpa Flow"],
["587156", "Cactus"],
["589AAF", "Hippie Blue"],
["591D35", "Wine Berry"],
["592804", "Brown Bramble"],
["593737", "Congo Brown"],
["594433", "Millbrook"],
["5A6E9C", "Waikawa Gray"],
["5A87A0", "Horizon"],
["5B3013", "Jambalaya"],
["5C0120", "Bordeaux"],
["5C0536", "Mulberry Wood"],
["5C2E01", "Carnaby Tan"],
["5C5D75", "Comet"],
["5D1E0F", "Redwood"],
["5D4C51", "Don Juan"],
["5D5C58", "Chicago"],
["5D5E37", "Verdigris"],
["5D7747", "Dingley"],
["5DA19F", "Breaker Bay"],
["5E483E", "Kabul"],
["5E5D3B", "Hemlock"],
["5F3D26", "Irish Coffee"],
["5F5F6E", "Mid Gray"],
["5F6672", "Shuttle Gray"],
["5FA777", "Aqua Forest"],
["5FB3AC", "Tradewind"],
["604913", "Horses Neck"],
["605B73", "Smoky"],
["606E68", "Corduroy"],
["6093D1", "Danube"],
["612718", "Espresso"],
["614051", "Eggplant"],
["615D30", "Costa Del Sol"],
["61845F", "Glade Green"],
["622F30", "Buccaneer"],
["623F2D", "Quincy"],
["624E9A", "Butterfly Bush"],
["625119", "West Coast"],
["626649", "Finch"],
["639A8F", "Patina"],
["63B76C", "Fern"],
["6456B7", "Blue Violet"],
["646077", "Dolphin"],
["646463", "Storm Dust"],
["646A54", "Siam"],
["646E75", "Nevada"],
["6495ED", "Cornflower Blue"],
["64CCDB", "Viking"],
["65000B", "Rosewood"],
["651A14", "Cherrywood"],
["652DC1", "Purple Heart"],
["657220", "Fern Frond"],
["65745D", "Willow Grove"],
["65869F", "Hoki"],
["660045", "Pompadour"],
["660099", "Purple"],
["66023C", "Tyrian Purple"],
["661010", "Dark Tan"],
["66B58F", "Silver Tree"],
["66FF00", "Bright Green"],
["66FF66", "Screamin' Green"],
["67032D", "Black Rose"],
["675FA6", "Scampi"],
["676662", "Ironside Gray"],
["678975", "Viridian Green"],
["67A712", "Christi"],
["683600", "Nutmeg Wood Finish"],
["685558", "Zambezi"],
["685E6E", "Salt Box"],
["692545", "Tawny Port"],
["692D54", "Finn"],
["695F62", "Scorpion"],
["697E9A", "Lynch"],
["6A442E", "Spice"],
["6A5D1B", "Himalaya"],
["6A6051", "Soya Bean"],
["6B2A14", "Hairy Heath"],
["6B3FA0", "Royal Purple"],
["6B4E31", "Shingle Fawn"],
["6B5755", "Dorado"],
["6B8BA2", "Bermuda Gray"],
["6B8E23", "Olive Drab"],
["6C3082", "Eminence"],
["6CDAE7", "Turquoise Blue"],
["6D0101", "Lonestar"],
["6D5E54", "Pine Cone"],
["6D6C6C", "Dove Gray"],
["6D9292", "Juniper"],
["6D92A1", "Gothic"],
["6E0902", "Red Oxide"],
["6E1D14", "Moccaccino"],
["6E4826", "Pickled Bean"],
["6E4B26", "Dallas"],
["6E6D57", "Kokoda"],
["6E7783", "Pale Sky"],
["6F440C", "Cafe Royale"],
["6F6A61", "Flint"],
["6F8E63", "Highland"],
["6F9D02", "Limeade"],
["6FD0C5", "Downy"],
["701C1C", "Persian Plum"],
["704214", "Sepia"],
["704A07", "Antique Bronze"],
["704F50", "Ferra"],
["706555", "Coffee"],
["708090", "Slate Gray"],
["711A00", "Cedar Wood Finish"],
["71291D", "Metallic Copper"],
["714693", "Affair"],
["714AB2", "Studio"],
["715D47", "Tobacco Brown"],
["716338", "Yellow Metal"],
["716B56", "Peat"],
["716E10", "Olivetone"],
["717486", "Storm Gray"],
["718080", "Sirocco"],
["71D9E2", "Aquamarine Blue"],
["72010F", "Venetian Red"],
["724A2F", "Old Copper"],
["726D4E", "Go Ben"],
["727B89", "Raven"],
["731E8F", "Seance"],
["734A12", "Raw Umber"],
["736C9F", "Kimberly"],
["736D58", "Crocodile"],
["737829", "Crete"],
["738678", "Xanadu"],
["74640D", "Spicy Mustard"],
["747D63", "Limed Ash"],
["747D83", "Rolling Stone"],
["748881", "Blue Smoke"],
["749378", "Laurel"],
["74C365", "Mantis"],
["755A57", "Russett"],
["7563A8", "Deluge"],
["76395D", "Cosmic"],
["7666C6", "Blue Marguerite"],
["76BD17", "Lima"],
["76D7EA", "Sky Blue"],
["770F05", "Dark Burgundy"],
["771F1F", "Crown of Thorns"],
["773F1A", "Walnut"],
["776F61", "Pablo"],
["778120", "Pacifika"],
["779E86", "Oxley"],
["77DD77", "Pastel Green"],
["780109", "Japanese Maple"],
["782D19", "Mocha"],
["782F16", "Peanut"],
["78866B", "Camouflage Green"],
["788A25", "Wasabi"],
["788BBA", "Ship Cove"],
["78A39C", "Sea Nymph"],
["795D4C", "Roman Coffee"],
["796878", "Old Lavender"],
["796989", "Rum"],
["796A78", "Fedora"],
["796D62", "Sandstone"],
["79DEEC", "Spray"],
["7A013A", "Siren"],
["7A58C1", "Fuchsia Blue"],
["7A7A7A", "Boulder"],
["7A89B8", "Wild Blue Yonder"],
["7AC488", "De York"],
["7B3801", "Red Beech"],
["7B3F00", "Cinnamon"],
["7B6608", "Yukon Gold"],
["7B7874", "Tapa"],
["7B7C94", "Waterloo "],
["7B8265", "Flax Smoke"],
["7B9F80", "Amulet"],
["7BA05B", "Asparagus"],
["7C1C05", "Kenyan Copper"],
["7C7631", "Pesto"],
["7C778A", "Topaz"],
["7C7B7A", "Concord"],
["7C7B82", "Jumbo"],
["7C881A", "Trendy Green"],
["7CA1A6", "Gumbo"],
["7CB0A1", "Acapulco"],
["7CB7BB", "Neptune"],
["7D2C14", "Pueblo"],
["7DA98D", "Bay Leaf"],
["7DC8F7", "Malibu"],
["7DD8C6", "Bermuda"],
["7E3A15", "Copper Canyon"],
["7F1734", "Claret"],
["7F3A02", "Peru Tan"],
["7F626D", "Falcon"],
["7F7589", "Mobster"],
["7F76D3", "Moody Blue"],
["7FFF00", "Chartreuse"],
["7FFFD4", "Aquamarine"],
["800000", "Maroon"],
["800B47", "Rose Bud Cherry"],
["801818", "Falu Red"],
["80341F", "Red Robin"],
["803790", "Vivid Violet"],
["80461B", "Russet"],
["807E79", "Friar Gray"],
["808000", "Olive"],
["808080", "Gray"],
["80B3AE", "Gulf Stream"],
["80B3C4", "Glacier"],
["80CCEA", "Seagull"],
["81422C", "Nutmeg"],
["816E71", "Spicy Pink"],
["817377", "Empress"],
["819885", "Spanish Green"],
["826F65", "Sand Dune"],
["828685", "Gunsmoke"],
["828F72", "Battleship Gray"],
["831923", "Merlot"],
["837050", "Shadow"],
["83AA5D", "Chelsea Cucumber"],
["83D0C6", "Monte Carlo"],
["843179", "Plum"],
["84A0A0", "Granny Smith"],
["8581D9", "Chetwode Blue"],
["858470", "Bandicoot"],
["859FAF", "Bali Hai"],
["85C4CC", "Half Baked"],
["860111", "Red Devil"],
["863C3C", "Lotus"],
["86483C", "Ironstone"],
["864D1E", "Bull Shot"],
["86560A", "Rusty Nail"],
["868974", "Bitter"],
["86949F", "Regent Gray"],
["871550", "Disco"],
["87756E", "Americano"],
["877C7B", "Hurricane"],
["878D91", "Oslo Gray"],
["87AB39", "Sushi"],
["885342", "Spicy Mix"],
["886221", "Kumera"],
["888387", "Suva Gray"],
["888D65", "Avocado"],
["893456", "Camelot"],
["893843", "Solid Pink"],
["894367", "Cannon Pink"],
["897D6D", "Makara"],
["8A3324", "Burnt Umber"],
["8A73D6", "True V"],
["8A8360", "Clay Creek"],
["8A8389", "Monsoon"],
["8A8F8A", "Stack"],
["8AB9F1", "Jordy Blue"],
["8B00FF", "Electric Violet"],
["8B0723", "Monarch"],
["8B6B0B", "Corn Harvest"],
["8B8470", "Olive Haze"],
["8B847E", "Schooner"],
["8B8680", "Natural Gray"],
["8B9C90", "Mantle"],
["8B9FEE", "Portage"],
["8BA690", "Envy"],
["8BA9A5", "Cascade"],
["8BE6D8", "Riptide"],
["8C055E", "Cardinal Pink"],
["8C472F", "Mule Fawn"],
["8C5738", "Potters Clay"],
["8C6495", "Trendy Pink"],
["8D0226", "Paprika"],
["8D3D38", "Sanguine Brown"],
["8D3F3F", "Tosca"],
["8D7662", "Cement"],
["8D8974", "Granite Green"],
["8D90A1", "Manatee"],
["8DA8CC", "Polo Blue"],
["8E0000", "Red Berry"],
["8E4D1E", "Rope"],
["8E6F70", "Opium"],
["8E775E", "Domino"],
["8E8190", "Mamba"],
["8EABC1", "Nepal"],
["8F021C", "Pohutukawa"],
["8F3E33", "El Salva"],
["8F4B0E", "Korma"],
["8F8176", "Squirrel"],
["8FD6B4", "Vista Blue"],
["900020", "Burgundy"],
["901E1E", "Old Brick"],
["907874", "Hemp"],
["907B71", "Almond Frost"],
["908D39", "Sycamore"],
["92000A", "Sangria"],
["924321", "Cumin"],
["926F5B", "Beaver"],
["928573", "Stonewall"],
["928590", "Venus"],
["9370DB", "Medium Purple"],
["93CCEA", "Cornflower"],
["93DFB8", "Algae Green"],
["944747", "Copper Rust"],
["948771", "Arrowtown"],
["950015", "Scarlett"],
["956387", "Strikemaster"],
["959396", "Mountain Mist"],
["960018", "Carmine"],
["964B00", "Brown"],
["967059", "Leather"],
["9678B6", "Purple Mountain's Majesty"],
["967BB6", "Lavender Purple"],
["96A8A1", "Pewter"],
["96BBAB", "Summer Green"],
["97605D", "Au Chico"],
["9771B5", "Wisteria"],
["97CD2D", "Atlantis"],
["983D61", "Vin Rouge"],
["9874D3", "Lilac Bush"],
["98777B", "Bazaar"],
["98811B", "Hacienda"],
["988D77", "Pale Oyster"],
["98FF98", "Mint Green"],
["990066", "Fresh Eggplant"],
["991199", "Violet Eggplant"],
["991613", "Tamarillo"],
["991B07", "Totem Pole"],
["996666", "Copper Rose"],
["9966CC", "Amethyst"],
["997A8D", "Mountbatten Pink"],
["9999CC", "Blue Bell"],
["9A3820", "Prairie Sand"],
["9A6E61", "Toast"],
["9A9577", "Gurkha"],
["9AB973", "Olivine"],
["9AC2B8", "Shadow Green"],
["9B4703", "Oregon"],
["9B9E8F", "Lemon Grass"],
["9C3336", "Stiletto"],
["9D5616", "Hawaiian Tan"],
["9DACB7", "Gull Gray"],
["9DC209", "Pistachio"],
["9DE093", "Granny Smith Apple"],
["9DE5FF", "Anakiwa"],
["9E5302", "Chelsea Gem"],
["9E5B40", "Sepia Skin"],
["9EA587", "Sage"],
["9EA91F", "Citron"],
["9EB1CD", "Rock Blue"],
["9EDEE0", "Morning Glory"],
["9F381D", "Cognac"],
["9F821C", "Reef Gold"],
["9F9F9C", "Star Dust"],
["9FA0B1", "Santas Gray"],
["9FD7D3", "Sinbad"],
["9FDD8C", "Feijoa"],
["A02712", "Tabasco"],
["A1750D", "Buttered Rum"],
["A1ADB5", "Hit Gray"],
["A1C50A", "Citrus"],
["A1DAD7", "Aqua Island"],
["A1E9DE", "Water Leaf"],
["A2006D", "Flirt"],
["A23B6C", "Rouge"],
["A26645", "Cape Palliser"],
["A2AAB3", "Gray Chateau"],
["A2AEAB", "Edward"],
["A3807B", "Pharlap"],
["A397B4", "Amethyst Smoke"],
["A3E3ED", "Blizzard Blue"],
["A4A49D", "Delta"],
["A4A6D3", "Wistful"],
["A4AF6E", "Green Smoke"],
["A50B5E", "Jazzberry Jam"],
["A59B91", "Zorba"],
["A5CB0C", "Bahia"],
["A62F20", "Roof Terracotta"],
["A65529", "Paarl"],
["A68B5B", "Barley Corn"],
["A69279", "Donkey Brown"],
["A6A29A", "Dawn"],
["A72525", "Mexican Red"],
["A7882C", "Luxor Gold"],
["A85307", "Rich Gold"],
["A86515", "Reno Sand"],
["A86B6B", "Coral Tree"],
["A8989B", "Dusty Gray"],
["A899E6", "Dull Lavender"],
["A8A589", "Tallow"],
["A8AE9C", "Bud"],
["A8AF8E", "Locust"],
["A8BD9F", "Norway"],
["A8E3BD", "Chinook"],
["A9A491", "Gray Olive"],
["A9ACB6", "Aluminium"],
["A9B2C3", "Cadet Blue"],
["A9B497", "Schist"],
["A9BDBF", "Tower Gray"],
["A9BEF2", "Perano"],
["A9C6C2", "Opal"],
["AA375A", "Night Shadz"],
["AA4203", "Fire"],
["AA8B5B", "Muesli"],
["AA8D6F", "Sandal"],
["AAA5A9", "Shady Lady"],
["AAA9CD", "Logan"],
["AAABB7", "Spun Pearl"],
["AAD6E6", "Regent St Blue"],
["AAF0D1", "Magic Mint"],
["AB0563", "Lipstick"],
["AB3472", "Royal Heath"],
["AB917A", "Sandrift"],
["ABA0D9", "Cold Purple"],
["ABA196", "Bronco"],
["AC8A56", "Limed Oak"],
["AC91CE", "East Side"],
["AC9E22", "Lemon Ginger"],
["ACA494", "Napa"],
["ACA586", "Hillary"],
["ACA59F", "Cloudy"],
["ACACAC", "Silver Chalice"],
["ACB78E", "Swamp Green"],
["ACCBB1", "Spring Rain"],
["ACDD4D", "Conifer"],
["ACE1AF", "Celadon"],
["AD781B", "Mandalay"],
["ADBED1", "Casper"],
["ADDFAD", "Moss Green"],
["ADE6C4", "Padua"],
["ADFF2F", "Green Yellow"],
["AE4560", "Hippie Pink"],
["AE6020", "Desert"],
["AE809E", "Bouquet"],
["AF4035", "Medium Carmine"],
["AF4D43", "Apple Blossom"],
["AF593E", "Brown Rust"],
["AF8751", "Driftwood"],
["AF8F2C", "Alpine"],
["AF9F1C", "Lucky"],
["AFA09E", "Martini"],
["AFB1B8", "Bombay"],
["AFBDD9", "Pigeon Post"],
["B04C6A", "Cadillac"],
["B05D54", "Matrix"],
["B05E81", "Tapestry"],
["B06608", "Mai Tai"],
["B09A95", "Del Rio"],
["B0E0E6", "Powder Blue"],
["B0E313", "Inch Worm"],
["B10000", "Bright Red"],
["B14A0B", "Vesuvius"],
["B1610B", "Pumpkin Skin"],
["B16D52", "Santa Fe"],
["B19461", "Teak"],
["B1E2C1", "Fringy Flower"],
["B1F4E7", "Ice Cold"],
["B20931", "Shiraz"],
["B2A1EA", "Biloba Flower"],
["B32D29", "Tall Poppy"],
["B35213", "Fiery Orange"],
["B38007", "Hot Toddy"],
["B3AF95", "Taupe Gray"],
["B3C110", "La Rioja"],
["B43332", "Well Read"],
["B44668", "Blush"],
["B4CFD3", "Jungle Mist"],
["B57281", "Turkish Rose"],
["B57EDC", "Lavender"],
["B5A27F", "Mongoose"],
["B5B35C", "Olive Green"],
["B5D2CE", "Jet Stream"],
["B5ECDF", "Cruise"],
["B6316C", "Hibiscus"],
["B69D98", "Thatch"],
["B6B095", "Heathered Gray"],
["B6BAA4", "Eagle"],
["B6D1EA", "Spindle"],
["B6D3BF", "Gum Leaf"],
["B7410E", "Rust"],
["B78E5C", "Muddy Waters"],
["B7A214", "Sahara"],
["B7A458", "Husk"],
["B7B1B1", "Nobel"],
["B7C3D0", "Heather"],
["B7F0BE", "Madang"],
["B81104", "Milano Red"],
["B87333", "Copper"],
["B8B56A", "Gimblet"],
["B8C1B1", "Green Spring"],
["B8C25D", "Celery"],
["B8E0F9", "Sail"],
["B94E48", "Chestnut"],
["B95140", "Crail"],
["B98D28", "Marigold"],
["B9C46A", "Wild Willow"],
["B9C8AC", "Rainee"],
["BA0101", "Guardsman Red"],
["BA450C", "Rock Spray"],
["BA6F1E", "Bourbon"],
["BA7F03", "Pirate Gold"],
["BAB1A2", "Nomad"],
["BAC7C9", "Submarine"],
["BAEEF9", "Charlotte"],
["BB3385", "Medium Red Violet"],
["BB8983", "Brandy Rose"],
["BBD009", "Rio Grande"],
["BBD7C1", "Surf"],
["BCC9C2", "Powder Ash"],
["BD5E2E", "Tuscany"],
["BD978E", "Quicksand"],
["BDB1A8", "Silk"],
["BDB2A1", "Malta"],
["BDB3C7", "Chatelle"],
["BDBBD7", "Lavender Gray"],
["BDBDC6", "French Gray"],
["BDC8B3", "Clay Ash"],
["BDC9CE", "Loblolly"],
["BDEDFD", "French Pass"],
["BEA6C3", "London Hue"],
["BEB5B7", "Pink Swan"],
["BEDE0D", "Fuego"],
["BF5500", "Rose of Sharon"],
["BFB8B0", "Tide"],
["BFBED8", "Blue Haze"],
["BFC1C2", "Silver Sand"],
["BFC921", "Key Lime Pie"],
["BFDBE2", "Ziggurat"],
["BFFF00", "Lime"],
["C02B18", "Thunderbird"],
["C04737", "Mojo"],
["C08081", "Old Rose"],
["C0C0C0", "Silver"],
["C0D3B9", "Pale Leaf"],
["C0D8B6", "Pixie Green"],
["C1440E", "Tia Maria"],
["C154C1", "Fuchsia Pink"],
["C1A004", "Buddha Gold"],
["C1B7A4", "Bison Hide"],
["C1BAB0", "Tea"],
["C1BECD", "Gray Suit"],
["C1D7B0", "Sprout"],
["C1F07C", "Sulu"],
["C26B03", "Indochine"],
["C2955D", "Twine"],
["C2BDB6", "Cotton Seed"],
["C2CAC4", "Pumice"],
["C2E8E5", "Jagged Ice"],
["C32148", "Maroon Flush"],
["C3B091", "Indian Khaki"],
["C3BFC1", "Pale Slate"],
["C3C3BD", "Gray Nickel"],
["C3CDE6", "Periwinkle Gray"],
["C3D1D1", "Tiara"],
["C3DDF9", "Tropical Blue"],
["C41E3A", "Cardinal"],
["C45655", "Fuzzy Wuzzy Brown"],
["C45719", "Orange Roughy"],
["C4C4BC", "Mist Gray"],
["C4D0B0", "Coriander"],
["C4F4EB", "Mint Tulip"],
["C54B8C", "Mulberry"],
["C59922", "Nugget"],
["C5994B", "Tussock"],
["C5DBCA", "Sea Mist"],
["C5E17A", "Yellow Green"],
["C62D42", "Brick Red"],
["C6726B", "Contessa"],
["C69191", "Oriental Pink"],
["C6A84B", "Roti"],
["C6C3B5", "Ash"],
["C6C8BD", "Kangaroo"],
["C6E610", "Las Palmas"],
["C7031E", "Monza"],
["C71585", "Red Violet"],
["C7BCA2", "Coral Reef"],
["C7C1FF", "Melrose"],
["C7C4BF", "Cloud"],
["C7C9D5", "Ghost"],
["C7CD90", "Pine Glade"],
["C7DDE5", "Botticelli"],
["C88A65", "Antique Brass"],
["C8A2C8", "Lilac"],
["C8A528", "Hokey Pokey"],
["C8AABF", "Lily"],
["C8B568", "Laser"],
["C8E3D7", "Edgewater"],
["C96323", "Piper"],
["C99415", "Pizza"],
["C9A0DC", "Light Wisteria"],
["C9B29B", "Rodeo Dust"],
["C9B35B", "Sundance"],
["C9B93B", "Earls Green"],
["C9C0BB", "Silver Rust"],
["C9D9D2", "Conch"],
["C9FFA2", "Reef"],
["C9FFE5", "Aero Blue"],
["CA3435", "Flush Mahogany"],
["CABB48", "Turmeric"],
["CADCD4", "Paris White"],
["CAE00D", "Bitter Lemon"],
["CAE6DA", "Skeptic"],
["CB8FA9", "Viola"],
["CBCAB6", "Foggy Gray"],
["CBD3B0", "Green Mist"],
["CBDBD6", "Nebula"],
["CC3333", "Persian Red"],
["CC5500", "Burnt Orange"],
["CC7722", "Ochre"],
["CC8899", "Puce"],
["CCCAA8", "Thistle Green"],
["CCCCFF", "Periwinkle"],
["CCFF00", "Electric Lime"],
["CD5700", "Tenn"],
["CD5C5C", "Chestnut Rose"],
["CD8429", "Brandy Punch"],
["CDF4FF", "Onahau"],
["CEB98F", "Sorrell Brown"],
["CEBABA", "Cold Turkey"],
["CEC291", "Yuma"],
["CEC7A7", "Chino"],
["CFA39D", "Eunry"],
["CFB53B", "Old Gold"],
["CFDCCF", "Tasman"],
["CFE5D2", "Surf Crest"],
["CFF9F3", "Humming Bird"],
["CFFAF4", "Scandal"],
["D05F04", "Red Stage"],
["D06DA1", "Hopbush"],
["D07D12", "Meteor"],
["D0BEF8", "Perfume"],
["D0C0E5", "Prelude"],
["D0F0C0", "Tea Green"],
["D18F1B", "Geebung"],
["D1BEA8", "Vanilla"],
["D1C6B4", "Soft Amber"],
["D1D2CA", "Celeste"],
["D1D2DD", "Mischka"],
["D1E231", "Pear"],
["D2691E", "Hot Cinnamon"],
["D27D46", "Raw Sienna"],
["D29EAA", "Careys Pink"],
["D2B48C", "Tan"],
["D2DA97", "Deco"],
["D2F6DE", "Blue Romance"],
["D2F8B0", "Gossip"],
["D3CBBA", "Sisal"],
["D3CDC5", "Swirl"],
["D47494", "Charm"],
["D4B6AF", "Clam Shell"],
["D4BF8D", "Straw"],
["D4C4A8", "Akaroa"],
["D4CD16", "Bird Flower"],
["D4D7D9", "Iron"],
["D4DFE2", "Geyser"],
["D4E2FC", "Hawkes Blue"],
["D54600", "Grenadier"],
["D591A4", "Can Can"],
["D59A6F", "Whiskey"],
["D5D195", "Winter Hazel"],
["D5F6E3", "Granny Apple"],
["D69188", "My Pink"],
["D6C562", "Tacha"],
["D6CEF6", "Moon Raker"],
["D6D6D1", "Quill Gray"],
["D6FFDB", "Snowy Mint"],
["D7837F", "New York Pink"],
["D7C498", "Pavlova"],
["D7D0FF", "Fog"],
["D84437", "Valencia"],
["D87C63", "Japonica"],
["D8BFD8", "Thistle"],
["D8C2D5", "Maverick"],
["D8FCFA", "Foam"],
["D94972", "Cabaret"],
["D99376", "Burning Sand"],
["D9B99B", "Cameo"],
["D9D6CF", "Timberwolf"],
["D9DCC1", "Tana"],
["D9E4F5", "Link Water"],
["D9F7FF", "Mabel"],
["DA3287", "Cerise"],
["DA5B38", "Flame Pea"],
["DA6304", "Bamboo"],
["DA6A41", "Red Damask"],
["DA70D6", "Orchid"],
["DA8A67", "Copperfield"],
["DAA520", "Golden Grass"],
["DAECD6", "Zanah"],
["DAF4F0", "Iceberg"],
["DAFAFF", "Oyster Bay"],
["DB5079", "Cranberry"],
["DB9690", "Petite Orchid"],
["DB995E", "Di Serria"],
["DBDBDB", "Alto"],
["DBFFF8", "Frosted Mint"],
["DC143C", "Crimson"],
["DC4333", "Punch"],
["DCB20C", "Galliano"],
["DCB4BC", "Blossom"],
["DCD747", "Wattle"],
["DCD9D2", "Westar"],
["DCDDCC", "Moon Mist"],
["DCEDB4", "Caper"],
["DCF0EA", "Swans Down"],
["DDD6D5", "Swiss Coffee"],
["DDF9F1", "White Ice"],
["DE3163", "Cerise Red"],
["DE6360", "Roman"],
["DEA681", "Tumbleweed"],
["DEBA13", "Gold Tips"],
["DEC196", "Brandy"],
["DECBC6", "Wafer"],
["DED4A4", "Sapling"],
["DED717", "Barberry"],
["DEE5C0", "Beryl Green"],
["DEF5FF", "Pattens Blue"],
["DF73FF", "Heliotrope"],
["DFBE6F", "Apache"],
["DFCD6F", "Chenin"],
["DFCFDB", "Lola"],
["DFECDA", "Willow Brook"],
["DFFF00", "Chartreuse Yellow"],
["E0B0FF", "Mauve"],
["E0B646", "Anzac"],
["E0B974", "Harvest Gold"],
["E0C095", "Calico"],
["E0FFFF", "Baby Blue"],
["E16865", "Sunglo"],
["E1BC64", "Equator"],
["E1C0C8", "Pink Flare"],
["E1E6D6", "Periglacial Blue"],
["E1EAD4", "Kidnapper"],
["E1F6E8", "Tara"],
["E25465", "Mandy"],
["E2725B", "Terracotta"],
["E28913", "Golden Bell"],
["E292C0", "Shocking"],
["E29418", "Dixie"],
["E29CD2", "Light Orchid"],
["E2D8ED", "Snuff"],
["E2EBED", "Mystic"],
["E2F3EC", "Apple Green"],
["E30B5C", "Razzmatazz"],
["E32636", "Alizarin Crimson"],
["E34234", "Cinnabar"],
["E3BEBE", "Cavern Pink"],
["E3F5E1", "Peppermint"],
["E3F988", "Mindaro"],
["E47698", "Deep Blush"],
["E49B0F", "Gamboge"],
["E4C2D5", "Melanie"],
["E4CFDE", "Twilight"],
["E4D1C0", "Bone"],
["E4D422", "Sunflower"],
["E4D5B7", "Grain Brown"],
["E4D69B", "Zombie"],
["E4F6E7", "Frostee"],
["E4FFD1", "Snow Flurry"],
["E52B50", "Amaranth"],
["E5841B", "Zest"],
["E5CCC9", "Dust Storm"],
["E5D7BD", "Stark White"],
["E5D8AF", "Hampton"],
["E5E0E1", "Bon Jour"],
["E5E5E5", "Mercury"],
["E5F9F6", "Polar"],
["E64E03", "Trinidad"],
["E6BE8A", "Gold Sand"],
["E6BEA5", "Cashmere"],
["E6D7B9", "Double Spanish White"],
["E6E4D4", "Satin Linen"],
["E6F2EA", "Harp"],
["E6F8F3", "Off Green"],
["E6FFE9", "Hint of Green"],
["E6FFFF", "Tranquil"],
["E77200", "Mango Tango"],
["E7730A", "Christine"],
["E79F8C", "Tonys Pink"],
["E79FC4", "Kobi"],
["E7BCB4", "Rose Fog"],
["E7BF05", "Corn"],
["E7CD8C", "Putty"],
["E7ECE6", "Gray Nurse"],
["E7F8FF", "Lily White"],
["E7FEFF", "Bubbles"],
["E89928", "Fire Bush"],
["E8B9B3", "Shilo"],
["E8E0D5", "Pearl Bush"],
["E8EBE0", "Green White"],
["E8F1D4", "Chrome White"],
["E8F2EB", "Gin"],
["E8F5F2", "Aqua Squeeze"],
["E96E00", "Clementine"],
["E97451", "Burnt Sienna"],
["E97C07", "Tahiti Gold"],
["E9CECD", "Oyster Pink"],
["E9D75A", "Confetti"],
["E9E3E3", "Ebb"],
["E9F8ED", "Ottoman"],
["E9FFFD", "Clear Day"],
["EA88A8", "Carissma"],
["EAAE69", "Porsche"],
["EAB33B", "Tulip Tree"],
["EAC674", "Rob Roy"],
["EADAB8", "Raffia"],
["EAE8D4", "White Rock"],
["EAF6EE", "Panache"],
["EAF6FF", "Solitude"],
["EAF9F5", "Aqua Spring"],
["EAFFFE", "Dew"],
["EB9373", "Apricot"],
["EBC2AF", "Zinnwaldite"],
["ECA927", "Fuel Yellow"],
["ECC54E", "Ronchi"],
["ECC7EE", "French Lilac"],
["ECCDB9", "Just Right"],
["ECE090", "Wild Rice"],
["ECEBBD", "Fall Green"],
["ECEBCE", "Aths Special"],
["ECF245", "Starship"],
["ED0A3F", "Red Ribbon"],
["ED7A1C", "Tango"],
["ED9121", "Carrot Orange"],
["ED989E", "Sea Pink"],
["EDB381", "Tacao"],
["EDC9AF", "Desert Sand"],
["EDCDAB", "Pancho"],
["EDDCB1", "Chamois"],
["EDEA99", "Primrose"],
["EDF5DD", "Frost"],
["EDF5F5", "Aqua Haze"],
["EDF6FF", "Zumthor"],
["EDF9F1", "Narvik"],
["EDFC84", "Honeysuckle"],
["EE82EE", "Lavender Magenta"],
["EEC1BE", "Beauty Bush"],
["EED794", "Chalky"],
["EED9C4", "Almond"],
["EEDC82", "Flax"],
["EEDEDA", "Bizarre"],
["EEE3AD", "Double Colonial White"],
["EEEEE8", "Cararra"],
["EEEF78", "Manz"],
["EEF0C8", "Tahuna Sands"],
["EEF0F3", "Athens Gray"],
["EEF3C3", "Tusk"],
["EEF4DE", "Loafer"],
["EEF6F7", "Catskill White"],
["EEFDFF", "Twilight Blue"],
["EEFF9A", "Jonquil"],
["EEFFE2", "Rice Flower"],
["EF863F", "Jaffa"],
["EFEFEF", "Gallery"],
["EFF2F3", "Porcelain"],
["F091A9", "Mauvelous"],
["F0D52D", "Golden Dream"],
["F0DB7D", "Golden Sand"],
["F0DC82", "Buff"],
["F0E2EC", "Prim"],
["F0E68C", "Khaki"],
["F0EEFD", "Selago"],
["F0EEFF", "Titan White"],
["F0F8FF", "Alice Blue"],
["F0FCEA", "Feta"],
["F18200", "Gold Drop"],
["F19BAB", "Wewak"],
["F1E788", "Sahara Sand"],
["F1E9D2", "Parchment"],
["F1E9FF", "Blue Chalk"],
["F1EEC1", "Mint Julep"],
["F1F1F1", "Seashell"],
["F1F7F2", "Saltpan"],
["F1FFAD", "Tidal"],
["F1FFC8", "Chiffon"],
["F2552A", "Flamingo"],
["F28500", "Tangerine"],
["F2C3B2", "Mandys Pink"],
["F2F2F2", "Concrete"],
["F2FAFA", "Black Squeeze"],
["F34723", "Pomegranate"],
["F3AD16", "Buttercup"],
["F3D69D", "New Orleans"],
["F3D9DF", "Vanilla Ice"],
["F3E7BB", "Sidecar"],
["F3E9E5", "Dawn Pink"],
["F3EDCF", "Wheatfield"],
["F3FB62", "Canary"],
["F3FBD4", "Orinoco"],
["F3FFD8", "Carla"],
["F400A1", "Hollywood Cerise"],
["F4A460", "Sandy brown"],
["F4C430", "Saffron"],
["F4D81C", "Ripe Lemon"],
["F4EBD3", "Janna"],
["F4F2EE", "Pampas"],
["F4F4F4", "Wild Sand"],
["F4F8FF", "Zircon"],
["F57584", "Froly"],
["F5C85C", "Cream Can"],
["F5C999", "Manhattan"],
["F5D5A0", "Maize"],
["F5DEB3", "Wheat"],
["F5E7A2", "Sandwisp"],
["F5E7E2", "Pot Pourri"],
["F5E9D3", "Albescent White"],
["F5EDEF", "Soft Peach"],
["F5F3E5", "Ecru White"],
["F5F5DC", "Beige"],
["F5FB3D", "Golden Fizz"],
["F5FFBE", "Australian Mint"],
["F64A8A", "French Rose"],
["F653A6", "Brilliant Rose"],
["F6A4C9", "Illusion"],
["F6F0E6", "Merino"],
["F6F7F7", "Black Haze"],
["F6FFDC", "Spring Sun"],
["F7468A", "Violet Red"],
["F77703", "Chilean Fire"],
["F77FBE", "Persian Pink"],
["F7B668", "Rajah"],
["F7C8DA", "Azalea"],
["F7DBE6", "We Peep"],
["F7F2E1", "Quarter Spanish White"],
["F7F5FA", "Whisper"],
["F7FAF7", "Snow Drift"],
["F8B853", "Casablanca"],
["F8C3DF", "Chantilly"],
["F8D9E9", "Cherub"],
["F8DB9D", "Marzipan"],
["F8DD5C", "Energy Yellow"],
["F8E4BF", "Givry"],
["F8F0E8", "White Linen"],
["F8F4FF", "Magnolia"],
["F8F6F1", "Spring Wood"],
["F8F7DC", "Coconut Cream"],
["F8F7FC", "White Lilac"],
["F8F8F7", "Desert Storm"],
["F8F99C", "Texas"],
["F8FACD", "Corn Field"],
["F8FDD3", "Mimosa"],
["F95A61", "Carnation"],
["F9BF58", "Saffron Mango"],
["F9E0ED", "Carousel Pink"],
["F9E4BC", "Dairy Cream"],
["F9E663", "Portica"],
["F9E6F4", "Underage Pink"],
["F9EAF3", "Amour"],
["F9F8E4", "Rum Swizzle"],
["F9FF8B", "Dolly"],
["F9FFF6", "Sugar Cane"],
["FA7814", "Ecstasy"],
["FA9D5A", "Tan Hide"],
["FAD3A2", "Corvette"],
["FADFAD", "Peach Yellow"],
["FAE600", "Turbo"],
["FAEAB9", "Astra"],
["FAECCC", "Champagne"],
["FAF0E6", "Linen"],
["FAF3F0", "Fantasy"],
["FAF7D6", "Citrine White"],
["FAFAFA", "Alabaster"],
["FAFDE4", "Hint of Yellow"],
["FAFFA4", "Milan"],
["FB607F", "Brink Pink"],
["FB8989", "Geraldine"],
["FBA0E3", "Lavender Rose"],
["FBA129", "Sea Buckthorn"],
["FBAC13", "Sun"],
["FBAED2", "Lavender Pink"],
["FBB2A3", "Rose Bud"],
["FBBEDA", "Cupid"],
["FBCCE7", "Classic Rose"],
["FBCEB1", "Apricot Peach"],
["FBE7B2", "Banana Mania"],
["FBE870", "Marigold Yellow"],
["FBE96C", "Festival"],
["FBEA8C", "Sweet Corn"],
["FBEC5D", "Candy Corn"],
["FBF9F9", "Hint of Red"],
["FBFFBA", "Shalimar"],
["FC0FC0", "Shocking Pink"],
["FC80A5", "Tickle Me Pink"],
["FC9C1D", "Tree Poppy"],
["FCC01E", "Lightning Yellow"],
["FCD667", "Goldenrod"],
["FCD917", "Candlelight"],
["FCDA98", "Cherokee"],
["FCF4D0", "Double Pearl Lusta"],
["FCF4DC", "Pearl Lusta"],
["FCF8F7", "Vista White"],
["FCFBF3", "Bianca"],
["FCFEDA", "Moon Glow"],
["FCFFE7", "China Ivory"],
["FCFFF9", "Ceramic"],
["FD0E35", "Torch Red"],
["FD5B78", "Wild Watermelon"],
["FD7B33", "Crusta"],
["FD7C07", "Sorbus"],
["FD9FA2", "Sweet Pink"],
["FDD5B1", "Light Apricot"],
["FDD7E4", "Pig Pink"],
["FDE1DC", "Cinderella"],
["FDE295", "Golden Glow"],
["FDE910", "Lemon"],
["FDF5E6", "Old Lace"],
["FDF6D3", "Half Colonial White"],
["FDF7AD", "Drover"],
["FDFEB8", "Pale Prim"],
["FDFFD5", "Cumulus"],
["FE28A2", "Persian Rose"],
["FE4C40", "Sunset Orange"],
["FE6F5E", "Bittersweet"],
["FE9D04", "California"],
["FEA904", "Yellow Sea"],
["FEBAAD", "Melon"],
["FED33C", "Bright Sun"],
["FED85D", "Dandelion"],
["FEDB8D", "Salomie"],
["FEE5AC", "Cape Honey"],
["FEEBF3", "Remy"],
["FEEFCE", "Oasis"],
["FEF0EC", "Bridesmaid"],
["FEF2C7", "Beeswax"],
["FEF3D8", "Bleach White"],
["FEF4CC", "Pipi"],
["FEF4DB", "Half Spanish White"],
["FEF4F8", "Wisp Pink"],
["FEF5F1", "Provincial Pink"],
["FEF7DE", "Half Dutch White"],
["FEF8E2", "Solitaire"],
["FEF8FF", "White Pointer"],
["FEF9E3", "Off Yellow"],
["FEFCED", "Orange White"],
["FF0000", "Red"],
["FF007F", "Rose"],
["FF00CC", "Purple Pizzazz"],
["FF00FF", "Magenta / Fuchsia"],
["FF2400", "Scarlet"],
["FF3399", "Wild Strawberry"],
["FF33CC", "Razzle Dazzle Rose"],
["FF355E", "Radical Red"],
["FF3F34", "Red Orange"],
["FF4040", "Coral Red"],
["FF4D00", "Vermilion"],
["FF4F00", "International Orange"],
["FF6037", "Outrageous Orange"],
["FF6600", "Blaze Orange"],
["FF66FF", "Pink Flamingo"],
["FF681F", "Orange"],
["FF69B4", "Hot Pink"],
["FF6B53", "Persimmon"],
["FF6FFF", "Blush Pink"],
["FF7034", "Burning Orange"],
["FF7518", "Pumpkin"],
["FF7D07", "Flamenco"],
["FF7F00", "Flush Orange"],
["FF7F50", "Coral"],
["FF8C69", "Salmon"],
["FF9000", "Pizazz"],
["FF910F", "West Side"],
["FF91A4", "Pink Salmon"],
["FF9933", "Neon Carrot"],
["FF9966", "Atomic Tangerine"],
["FF9980", "Vivid Tangerine"],
["FF9E2C", "Sunshade"],
["FFA000", "Orange Peel"],
["FFA194", "Mona Lisa"],
["FFA500", "Web Orange"],
["FFA6C9", "Carnation Pink"],
["FFAB81", "Hit Pink"],
["FFAE42", "Yellow Orange"],
["FFB0AC", "Cornflower Lilac"],
["FFB1B3", "Sundown"],
["FFB31F", "My Sin"],
["FFB555", "Texas Rose"],
["FFB7D5", "Cotton Candy"],
["FFB97B", "Macaroni and Cheese"],
["FFBA00", "Selective Yellow"],
["FFBD5F", "Koromiko"],
["FFBF00", "Amber"],
["FFC0A8", "Wax Flower"],
["FFC0CB", "Pink"],
["FFC3C0", "Your Pink"],
["FFC901", "Supernova"],
["FFCBA4", "Flesh"],
["FFCC33", "Sunglow"],
["FFCC5C", "Golden Tainoi"],
["FFCC99", "Peach Orange"],
["FFCD8C", "Chardonnay"],
["FFD1DC", "Pastel Pink"],
["FFD2B7", "Romantic"],
["FFD38C", "Grandis"],
["FFD700", "Gold"],
["FFD800", "School bus Yellow"],
["FFD8D9", "Cosmos"],
["FFDB58", "Mustard"],
["FFDCD6", "Peach Schnapps"],
["FFDDAF", "Caramel"],
["FFDDCD", "Tuft Bush"],
["FFDDCF", "Watusi"],
["FFDDF4", "Pink Lace"],
["FFDEAD", "Navajo White"],
["FFDEB3", "Frangipani"],
["FFE1DF", "Pippin"],
["FFE1F2", "Pale Rose"],
["FFE2C5", "Negroni"],
["FFE5A0", "Cream Brulee"],
["FFE5B4", "Peach"],
["FFE6C7", "Tequila"],
["FFE772", "Kournikova"],
["FFEAC8", "Sandy Beach"],
["FFEAD4", "Karry"],
["FFEC13", "Broom"],
["FFEDBC", "Colonial White"],
["FFEED8", "Derby"],
["FFEFA1", "Vis Vis"],
["FFEFC1", "Egg White"],
["FFEFD5", "Papaya Whip"],
["FFEFEC", "Fair Pink"],
["FFF0DB", "Peach Cream"],
["FFF0F5", "Lavender blush"],
["FFF14F", "Gorse"],
["FFF1B5", "Buttermilk"],
["FFF1D8", "Pink Lady"],
["FFF1EE", "Forget Me Not"],
["FFF1F9", "Tutu"],
["FFF39D", "Picasso"],
["FFF3F1", "Chardon"],
["FFF46E", "Paris Daisy"],
["FFF4CE", "Barley White"],
["FFF4DD", "Egg Sour"],
["FFF4E0", "Sazerac"],
["FFF4E8", "Serenade"],
["FFF4F3", "Chablis"],
["FFF5EE", "Seashell Peach"],
["FFF5F3", "Sauvignon"],
["FFF6D4", "Milk Punch"],
["FFF6DF", "Varden"],
["FFF6F5", "Rose White"],
["FFF8D1", "Baja White"],
["FFF9E2", "Gin Fizz"],
["FFF9E6", "Early Dawn"],
["FFFACD", "Lemon Chiffon"],
["FFFAF4", "Bridal Heath"],
["FFFBDC", "Scotch Mist"],
["FFFBF9", "Soapstone"],
["FFFC99", "Witch Haze"],
["FFFCEA", "Buttery White"],
["FFFCEE", "Island Spice"],
["FFFDD0", "Cream"],
["FFFDE6", "Chilean Heath"],
["FFFDE8", "Travertine"],
["FFFDF3", "Orchid White"],
["FFFDF4", "Quarter Pearl Lusta"],
["FFFEE1", "Half and Half"],
["FFFEEC", "Apricot White"],
["FFFEF0", "Rice Cake"],
["FFFEF6", "Black White"],
["FFFEFD", "Romance"],
["FFFF00", "Yellow"],
["FFFF66", "Laser Lemon"],
["FFFF99", "Pale Canary"],
["FFFFB4", "Portafino"],
["FFFFF0", "Ivory"],
["FFFFFF", "White"]
],

wikis : [
["000000","Black]]|html_name=Black|web_safe={{yes"],
["000080","Navy blue"],
["00008B","Blue#Dark blue|Dark blue"],
["00009C","Duke blue"],
["0000CD","Dark blue (color)#Medium blue|Medium blue"],
["0000FF","Blue]]|html_name=Blue|web_safe={{yes"],
["000F89","Phthalocyanine Blue BN|Phthalo blue"],
["0014A8","Zaffre"],
["002147","Oxford University|Oxford Blue"],
["002366","Royal blue|Royal blue (traditional)"],
["002387","Shades of blue#Resolution blue|Resolution blue"],
["002395","Indigo#Imperial blue|Imperial blue"],
["002E63","Rich black|Cool black"],
["002FA7","International Klein Blue"],
["00308F","Air Force blue#USAF blue|Air Force blue (USAF)"],
["003153","Prussian blue"],
["003366","Midnight blue#Dark midnight blue|Dark midnight blue"],
["003399","Powder blue#Dark powder blue (smalt)|Dark powder blue"],
["003399","Powder blue|Smalt (Dark powder blue)]]|web_safe={{yes"],
["0033AA","University of Arizona#School colors|UA blue"],
["0038A8","Azure (color)#Royal azure|Royal azure"],
["004040","Rich black"],
["00416A","Indigo#Dark imperial blue|Dark imperial blue"],
["00416A","Indigo#Indigo dye|Indigo (dye)"],
["004225","British racing green"],
["004242","Rich black|Warm black"],
["0047AB","Cobalt blue|Cobalt"],
["004953","Shades of green#Midnight green|Midnight green (eagle green)]]||web_safe={{yes"],
["004B49","Jungle green#Deep jungle green|Deep jungle green"],
["004F98","Air Force blue#USAFA blue|USAFA blue"],
["00563F","Shades of green#Castleton green|Castleton green"],
["00563F","Shades of green#Sacramento State green|Sacramento State green"],
["006600","Shades of green#Pakistan green|Pakistan green"],
["0067A5","Persian blue#Medium Persian blue|Medium Persian blue"],
["0067A5","Sapphire (color)#Sapphire blue|Sapphire blue"],
["006994","Shades of blue#Sea blue|Sea blue"],
["006A4E","Bottle green"],
["006B3C","Cadmium pigments|Cadmium green"],
["006DB0","Azure (color)#Honolulu blue|Honolulu blue"],
["00703C","Shades of green#Dartmouth green|Dartmouth green"],
["0070FF","Brandeis blue"],
["0072BB","Azure (color)#French blue|French blue"],
["0073CF","True Blue (color)|True Blue"],
["007474","Spring green (color)#Skobeloff|Skobeloff"],
["00755E","Jungle green#Tropical rain forest|Tropical rain forest"],
["0077BE","Azure (color)#Ocean boat blue|Ocean Boat Blue"],
["007AA5","CG Blue"],
["007BA7","Celadon (color)#Celadon Blue|Celadon blue"],
["007BA7","Cerulean"],
["007BB8","Cadet grey#Star command blue|Star command blue"],
["007FFF","Azure (color)|Azure"],
["008000","Ao (color)|Ao (English)"],
["008000","Shades of green#Office green|Office green]]|html_name=Gre"],
["008000","Variations of green|Green (HTML/CSS color)]]|html_name=Gre"],
["008080","Teal (color)#Teal|Teal]]|html_name=Te"],
["00827F","Teal (color)#Teal green|Teal green"],
["0087BD","Shades of blue#Blue (NCS)|Blue (NCS)"],
["008B8B","Cyan#Dark cyan|Dark cyan"],
["009000","Shades of green#Islamic green|Islamic green"],
["0093AF","Shades of blue#Blue (Munsell)|Blue (Munsell)"],
["0095B6","Bondi blue"],
["009E60","Shades of green#Shamrock green|Shamrock green"],
["009F6B","Shades of green#Green (NCS)|Green (NCS)"],
["00A550","Shades of green#Green (CMYK) (pigment green)|Green (pigment)"],
["00A693","Shades of green#Persian green|Persian green"],
["00A86B","Shades of green#Jade|Jade"],
["00A877","Shades of green#Green (Munsell)|Green (Munsell)"],
["00AAE4","Sky blue#Spanish sky blue|Spanish sky blue"],
["00AB66","Shades of green#GO Transit green|GO green"],
["00B7EB","Cyan|Cyan (process)"],
["00BFFF","Deep sky blue|Capri"],
["00BFFF","Sky blue#Deep sky blue|Deep sky blue"],
["00CC99","Spring green (color)#Caribbean green|Caribbean green"],
["00CCCC","Robin egg blue]]|web_safe={{yes"],
["00CCFF","Sky blue#Vivid sky blue|Vivid sky blue"],
["00CED1","Turquoise (color)#Dark Turquoise|Dark turquoise"],
["00FA9A","Spring green (color)#Medium spring green|Medium spring green"],
["00FF00","Electric green#Green (X11 color)|Electric green]]|web_safe={{yes"],
["00FF00","Lime (color)#Web color 'lime' (X11 Green)|Lime (web) (X11 green)]]|html_name=Lime|web_safe={{yes"],
["00FF00","Shades of green#Green (RGB) (X11 green) (HTML/CSS lime) (color wheel green) (electric green)|Green (color wheel) (X11 green)]]|html_name=Li"],
["00FF7F","List of Crayola colored pencil colors|Guppie green"],
["00FF7F","Spring green (color)|Spring green"],
["00FFEF","Turquoise (color)#Turquoise Blue|Turquoise blue"],
["00FFFF","Aqua (color)|Aqua]]|HTML name=Aq"],
["00FFFF","Cyan#Electric cyan vs. process cyan|Electric cyan"],
["00FFFF","Cyan]]|html_name=Cyan|web_safe={{yes"],
["013220","Dark green"],
["014421","Shades of green#UP Forest Green|Forest green (traditional)"],
["014421","Shades of green#UP Forest Green|UP Forest green"],
["01796F","Shades of green#Pine green|Pine green"],
["0247FE","RYB color model|Blue (RYB)"],
["035096","Electric blue (color)#Medium electric blue|Medium electric blue"],
["03C03C","Dark pastel green"],
["059033","ttp://www.unt.edu/identityguide/web-electronic.htm North Texas Gree"],
["062A78","Shades of blue#Catalina blue|Catalina blue"],
["08457E","Cerulean#Dark cerulean|Dark cerulean"],
["087830","De La Salle University|La Salle Green"],
["0892D0","Electric blue (color)#Rich electric blue|Rich electric blue"],
["08E8DE","Turquoise (color)#Bright Turquoise|Bright turquoise"],
["0A7E8C","List of Crayola crayon colors#Metallic FX|Metallic Seaweed"],
["0ABAB5","Tiffany Blue#Tiffany Blue|Tiffany Blue"],
["0BDA51","Shades of green#Malachite|Malachite"],
["0D98BA","Blue-green"],
["0F4D92","Yale Blue"],
["0F52BA","Sapphire (color)#Sapphire|Sapphire"],
["0FC0FC","List of Crayola colored pencil colors|Spiro Disco Ball"],
["100C08","Smoky black"],
["1034A6","Egyptian blue"],
["120A8F","Ultramarine"],
["123524","Phthalocyanine Green G|Phthalo green"],
["126180","Sapphire (color)#Blue sapphire|Blue sapphire"],
["138808","Shades of green#India green|India green"],
["1560BD","List of Crayola crayon colors#Standard colors|Denim"],
["177245","Spring green (color)#Dark spring green|Dark spring green"],
["18453B","Shades of green#MSU Green|MSU Green]]|web_safe={{yes"],
["191970","Midnight blue]]|web_safe={{yes"],
["195905","Lincoln green"],
["1A1110","Shades of black (colors)#Licorice|Licorice"],
["1A2421","Jungle green#Dark jungle green|Dark jungle green"],
["1B4D3E","Shades of green#Brunswick green|Brunswick green"],
["1B4D3E","Shades of green#Brunswick green|English green"],
["1C1CF0","Bluebonnet (plant)|Bluebonnet"],
["1C2841","Shades of blue|Yankees blue"],
["1C352D","Jungle green#Medium jungle green|Medium jungle green"],
["1C39BB","Persian blue"],
["1CAC78","List of Crayola crayon colors#Standard colors|Green (Crayola)"],
["1D2951","Cadet grey#Space cadet|Space cadet"],
["1DACD6","Cerulean#Bright cerulean|Bright cerulean"],
["1E4D2B","Shades of green#Cal Poly green|Cal Poly green"],
["1E90FF","Dodger blue"],
["1F75FE","List of Crayola crayon colors#Standard colors|Blue (Crayola)"],
["20B2AA","Cyan#Light sea green|Light sea green"],
["214FC6","List of Crayola crayon colors#Magic Scent|New Car"],
["21ABCD","List of Crayola colored pencil colors#Standard colors|Ball blue"],
["228B22","Shades of green#Forest green|Forest green (web)"],
["23297A","St. Patrick's blue"],
["232B2B","Shades of black (colors)#Charleston green|Charleston green"],
["253529","Shades of black (colors)#Black leather jacket|Black leather jacket"],
["264348","Indigo#Japanese indigo|Japanese indigo"],
["26619C","Azure (color)#Lapis lazuli|Lapis lazuli"],
["273BE2","Palatinate (colour)#Palatinate Blue|Palatinate blue"],
["29AB87","Jungle green"],
["2A52BE","Cerulean#Cerulean blue pigment|Cerulean blue"],
["2A8000","British racing green|Napier green"],
["2C1608","Zinnwaldite|Zinnwaldite brown"],
["2E5894","List of Crayola crayon colors#Metallic FX|B'dazzled Blue"],
["2E8B57","Shades of green#Sea green|Sea green"],
["2F4F4F","Slate gray#Dark slate gray|Dark slate gray"],
["2F847C","Shades of green#Celadon Green|Celadon green"],
["306030","Moss green#Mughal green|Mughal green"],
["30BA8F","List of Crayola crayon colors#Standard colors|Mountain Meadow"],
["30D5C8","Turquoise (color)|Turquoise]]|html_name=Turquoi"],
["317873","Shades of green#Myrtle green|Myrtle green"],
["318CE7","Bleu de France (colour)|Bleu de France"],
["319177","List of Crayola crayon colors#Metallic FX|Illuminating Emerald"],
["32127A","Persian blue#Persian indigo|Persian indigo"],
["321414","Seal brown"],
["32174D","Shades of violet#Russian violet|Russian violet"],
["324AB2","Indigo#Violet-blue|Violet-blue"],
["32CD32","Lime (color)#Lime green|Lime green"],
["333399","Shades of blue#Blue (CMYK) (pigment blue)|Blue (pigment)"],
["343434","Shades of black (colors)#Jet|Jet"],
["353839","Shades of black (colors)#Onyx|Onyx"],
["355E3B","Moss green#Deep moss green|Deep moss green"],
["355E3B","Shades of green#Hunter green|Hunter green"],
["36454F","Charcoal (color)|Charcoal"],
["367588","Teal (color)#Teal blue|Teal blue"],
["39A78E","Spring green#Zomp|Zomp"],
["39FF14","Shades of green#Neon green|Neon green"],
["3AB09E","Variations of cyan#Keppel|Keppel"],
["3B3C36","Olive (color)#Black olive|Black olive"],
["3B444B","sen"],
["3B7A57","Jungle green#Amazon|Amazon"],
["3C1414","Sienna|Dark sienna"],
["3C341F","Olive (color)#Olive drab|Olive Drab #7"],
["3CB371","Spring green (color)#Medium sea green|Medium sea green"],
["3CD070","List of Crayola colored pencil colors#Standard colors|UFO Green"],
["3D0C02","Shades of black (colors)#Black bean|Black bean"],
["3D2B1F","Bistre"],
["3EB489","Spring green (color)#Mint|Mint"],
["3F00FF","Ultramarine#Electric ultramarine|Electric ultramarine"],
["3FFF00","Shades of green#Harlequin|Harlequin"],
["40826D","Viridian"],
["414A4C","Shades of black (colors)#Outer space|Outer Space"],
["4166F5","Ultramarine#Ultramarine blue|Ultramarine blue"],
["4169E1","Royal blue|Royal blue (web)"],
["417DC1","Tufts Blue"],
["43302E","Burgundy (color)#Old burgundy|Old burgundy"],
["436B95","Royal blue#Queen blue|Queen blue"],
["43B3AE","Verdigris"],
["444C38","Shades of green#Rifle green|Rifle green"],
["446CCF","Han blue"],
["44D7A8","List of Crayola crayon colors#Magic Scent|Eucalyptus"],
["465945","Shades of green#Gray-asparagus|Gray-asparagus"],
["4682B4","Steel blue"],
["480607","Rose (color)#Bulgarian Rose|Bulgarian rose"],
["483C32","Lava (color)#Dark lava|Dark lava"],
["483C32","Taupe"],
["483C32","Taupe#Dark taupe|Dark taupe"],
["483D8B","X11 color names#Color names|Dark slate blue"],
["48D1CC","Turquoise (color)#Medium Turquoise|Medium turquoise"],
["49796B","Hooker's green"],
["4997D0","Azure (color)#Celestial blue|Celestial blue"],
["4A5D23","Moss green#Dark moss green|Dark moss green"],
["4A646C","List of Crayola crayon colors#Metallic FX|Deep Space Sparkle"],
["4B0082","Indigo#Pigment indigo (web color indigo)|Indigo (web)"],
["4B3621","Coffee (color)#Café Noir|Café noir"],
["4B5320","Shades of green#Army green|Army green"],
["4CBB17","Shades of green#Kelly green|Kelly green"],
["4D5D53","Shades of green#Feldgrau|Feldgrau"],
["4F666A","Stormcloud"],
["4F7942","Shades of green#Fern green|Fern green"],
["4F86F7","List of Crayola crayon colors#Magic Scent|Blueberry"],
["50404D","Taupe#Purple taupe|Purple taupe"],
["5072A7","Air Force blue#Blue yonder|Blue yonder"],
["507D2A","Shades of green#Sap green|Sap green"],
["50C878","Paris Green"],
["50C878","Shades of green#Emerald|Emerald"],
["51484F","Quartz"],
["5218FA","Han purple"],
["522D80","Regalia"],
["534B4F","Liver (color)#Dark liver (web)|Dark liver"],
["536872","Cadet grey#Cadet|Cadet"],
["536878","Electric blue (color)#Dark electric blue|Dark electric blue"],
["536878","Payne's grey"],
["536895","UCLA Blue"],
["543D37","Liver (color)#Dark liver (horses)|Dark liver (horses)"],
["555555","Davy's grey"],
["555D50","Shades of black (colors)#Ebony|Ebony"],
["556B2F","Chartreuse (color)#Dark olive green|Dark olive green"],
["560319","Scarlet (color)#Dark scarlet|Dark scarlet"],
["563C5C","Shades of violet#English violet|English violet"],
["568203","Chartreuse (color)#Avocado|Avocado"],
["58427C","List of Crayola crayon colors#Metallic FX|Cyber grape"],
["592720","Caput mortuum"],
["5A4FCF","Iris (color)|Iris"],
["5B3256","Shades of violet#Japanese violet|Japanese violet"],
["5B92E5","Azure (color)#United Nations blue|United Nations blue"],
["5D3954","Byzantium (color)#Dark byzantium|Dark byzantium"],
["5D89BA","Azure (color)#Silver Lake blue|Silver Lake blue"],
["5D8AA8","Air Force blue#RAF blue|Air Force blue (RAF)"],
["5D8AA8","Rackley"],
["5F9EA0","Cadet grey#Cadet blue|Cadet blue"],
["602F6B","Byzantium (color)#Imperial|Imperial"],
["6050DC","Majorelle Blue"],
["6082B6","Glaucous"],
["614051","Eggplant (color)|Eggplant"],
["635147","Umber#Umber|Umber"],
["645452","Wenge (colour)|Wenge"],
["6495ED","Cornflower blue"],
["65000B","Rose (color)#Rosewood|Rosewood"],
["654321","Brown#Dark brown|Dark brown"],
["654321","Brown#Otter brown|Otter brown"],
["66023C","Purple#Tyrian purple: Classical antiquity|Imperial purple"],
["66023C","Tyrian purple#Tyrian purple|Tyrian purple"],
["663854","Lavender (color)#Halayà úbe|Halayà úbe"],
["66424D","Tuscan red#Deep Tuscan red|Deep Tuscan red"],
["664C28","Shades of brown|Donkey Brown"],
["665D1E","Bronze (color)#Antique bronze|Antique bronze"],
["666699","Blue-gray#Dark blue-gray|Dark blue-gray"],
["6699CC","Blue-gray"],
["66B032","RYB color model|Green (RYB)"],
["66DDAA","Aquamarine (color)#Medium aquamarine|Medium aquamarine"],
["66FF00","Shades of green#Bright green|Bright green]]|web_safe={{yes"],
["673147","Mauve#Old mauve|Old mauve"],
["673147","Wine (color)#Wine dregs|Wine dregs"],
["674846","Rose (color)#Rose Ebony|Rose ebony"],
["674C47","Liver (color)|Liver"],
["674C47","Taupe#Medium taupe|Medium taupe"],
["679267","Shades of green#Russian green|Russian green"],
["682860","Palatinate (colour)#Palatinate Purple|Palatinate purple"],
["69359C","Purple Heart"],
["696969","Grey#Web colors|Dim gray"],
["6A5ACD","X11 color names#Color names|Slate blue"],
["6B4423","Brown#Brown-nose|Brown-nose"],
["6B4423","Brown#Brown-nose|Flattery"],
["6B8E23","Olive (color)#Olive drab|Olive Drab (web) (Olive Drab #3)"],
["6C2E1F","Liver (color)#Liver (organ)|Liver (organ)"],
["6C541E","Desert sand (color)#Field drab|Field drab"],
["6CA0DC","Baby blue#Little boy blue|Little boy blue"],
["6D9BC3","Cerulean#Cerulean frost|Cerulean frost"],
["6E7F80","List of Crayola colored pencil colors#Standard colors|AuroMetalSaurus"],
["6F00FF","Indigo#Electric indigo|Electric indigo"],
["6F00FF","Indigo#Electric indigo|Indigo"],
["6F2DA8","List of Crayola crayon colors#Magic Scent|Grape"],
["6F4E37","Coffee (color)|Coffee"],
["6F4E37","Tuscan red#Tuscan brown|Tuscan brown"],
["701C1C","Plum (color)#Persian plum (prune)|Persian plum"],
["701C1C","Plum (color)#Persian plum (prune)|Prune"],
["702963","Byzantium (color)|Byzantium"],
["703642","Catawba (grape)#Catawba (color)|Catawba"],
["704214","Sepia (color)|Sepia"],
["704241","Coffee (color)#Deep coffee|Deep coffee"],
["708090","Slate gray"],
["71A6D2","Blue-gray#Iceberg|Iceberg"],
["722F37","Wine (color)|Wine"],
["72A0C1","Air Force blue#Air superiority blue|Air superiority blue"],
["734F96","Lavender (color)#Dark lavender|Dark lavender"],
["737000","List of Crayola colored pencil colors#Standard colors|Bronze Yellow"],
["738276","List of Crayola crayon colors#Magic Scent|Smoke"],
["738678","Variations of gray#Xanadu|Xanadu"],
["73A9C2","Moonstone (gemstone)|Moonstone blue"],
["73C2FB","Maya Blue|Maya blue"],
["746CC0","List of Crayola colored pencil colors#Standard colors|Toolbox"],
["74C365","Shades of green#Mantis|Mantis"],
["757575","Silver (color)#Sonic silver|Sonic silver"],
["76FF7A","List of Crayola crayon colors#Standard colors|Screamin' Green"],
["777696","Blue-gray#Rhythm|Rhythm"],
["778899","Slate gray#Light slate gray|Light slate gray"],
["779ECB","Blue#Dark pastel blue|Dark pastel blue"],
["77B5FE","Sky blue#French sky blue|French sky blue"],
["77DD77","Pastel green"],
["78184A","Purple#Pansy purple|Pansy purple"],
["7851A9","Purple#Royal purple: 1600s|Royal purple"],
["78866B","Chartreuse (color)#Camouflage green|Camouflage green"],
["79443B","Bole (color)|Bole"],
["79443B","Tuscan red#Medium Tuscan red|Medium Tuscan red"],
["796878","Lavender (color)#Old lavender|Old lavender"],
["7B1113","Maroon (color)#UP maroon|UP Maroon"],
["7B3F00","Chocolate (color)|Chocolate (traditional)"],
["7B68EE","X11 color names#Color names|Medium slate blue"],
["7C0A02","Shades of red#Barn red|Barn red"],
["7C1C05","Copper (color)#Kenyan copper|Kenyan copper"],
["7C4848","Tuscan red"],
["7CB9E8","Air Force blue#Aero|Aero"],
["7CFC00","Chartreuse (color)#Lawn green|Lawn green"],
["7DF9FF","Electric blue (color)|Electric blue"],
["7E5E60","Taupe#Deep taupe|Deep Taupe"],
["7F00FF","Shades of violet#Color wheel violet|Violet (color wheel)"],
["7F1734","Wine (color)#Claret|Claret"],
["7FFF00","Chartreuse (color)|Chartreuse (web)"],
["7FFFD4","Aquamarine (color)|Aquamarine"],
["800000","Maroon (color)|Maroon (HTML/CSS)]]|html_name=Maro"],
["800020","Burgundy (color)|Burgundy"],
["800080","Purple#Purple (HTML/CSS color) (patriarch)|Patriarch"],
["800080","Purple#Purple (HTML/CSS color) (patriarch)|Purple (HTML/CSS)]]|html_name=Purp"],
["801818","Falu red"],
["80461B","Russet (color)|Russet"],
["80755A","Bistre#Spanish bistre|Spanish bistre"],
["808000","Gold|Heart Gold"],
["808000","Olive (color)|Olive"],
["808080","Grey|Gray]]|html_name=Gr"],
["808080","Grey|Trolley Grey"],
["808080","Variations of gray#Gray|Gray (HTML/CSS gray)"],
["80DAEB","Sky blue#Medium sky blue|Medium sky blue"],
["826644","Umber#Raw umber|Raw umber"],
["836953","Brown#Pastel brown|Pastel brown"],
["838996","Silver (color)#Roman silver|Roman silver"],
["841B2D","Ruby (color)#Antique ruby|Antique ruby"],
["843F5B","Ruby (color)#Deep ruby|Deep ruby"],
["848482","Battleship grey"],
["848482","Silver (color)#Old silver|Old silver"],
["856088","Shades of violet#Chinese violet|Chinese violet"],
["856D4D","Bistre#French bistre|French bistre"],
["85754E","List of Crayola crayon colors#Metallic FX|Gold Fusion"],
["85BB65","List of Crayola colored pencil colors#Standard colors|Dollar bill"],
["860111","Crimson#Red devil|Red devil"],
["8601AF","RYB color model|Violet (RYB)"],
["86608E","Lilac (color)#French lilac|French lilac"],
["86608E","Purple#Pomp and Power|Pomp and Power"],
["867E36","Moss green#Old moss green|Old moss green"],
["872657","Raspberry (color)#Dark raspberry|Dark raspberry"],
["873260","Boysenberry (color)|Boysenberry"],
["87A96B","Shades of green#Asparagus|Asparagus"],
["87CEEB","Sky blue"],
["87CEFA","Sky blue#Light sky blue|Light sky blue"],
["880085","Purple#Mardi Gras|Mardi Gras"],
["882D17","Indian red (color)#Kobe|Kobe"],
["882D17","Sienna"],
["8878C3","Lavender (color)#Úbe|Ube"],
["88D8C0","Aqua (color)|Pearl Aqua"],
["893F45","Cordovan (color)|Cordovan"],
["89CFF0","Baby blue"],
["8A2BE2","Indigo#Deep indigo (web color blue-violet)|Blue-violet"],
["8A3324","Burnt umber"],
["8A496B","Lavender (color)#Twilight lavender|Twilight lavender"],
["8A795D","List of Crayola crayon colors#Standard colors|Shadow"],
["8A7F80","Variations of gray#Rocket metallic|Rocket metallic"],
["8A9A5B","Moss green"],
["8B0000","Maroon (color)#Dark red|Dark red"],
["8B008B","Variations of magenta#Dark magenta|Dark magenta"],
["8B4513","X11 color names#Color name charts|Saddle brown"],
["8B8589","Taupe#Taupe gray|Taupe gray"],
["8C92AC","Cool grey"],
["8C92AC","Variations of gray#Cool gray|Gray-blue"],
["8CBED6","Sky blue#Dark sky blue|Dark sky blue"],
["8D4E85","List of Crayola crayon colors#Metallic FX|Razzmic Berry"],
["8DB600","Chartreuse (color)#Apple green|Apple green"],
["8E4585","Plum (color)|Plum (traditional)"],
["8F00FF","Violet (color)#Electric violet|Electric violet"],
["8F00FF","Violet (color)|Violet"],
["8FBC8F","X11 color names#Color names|Dark sea green"],
["8FD400","List of Crayola crayon colors#Metallic FX|Sheen Green"],
["905D5D","Taupe#Rose taupe|Rose taupe"],
["90EE90","X11 color names#Color names|Light green"],
["915C83","Fuchsia (color)#Antique fuchsia|Antique fuchsia"],
["915F6D","Raspberry (color)#Raspberry glace|Raspberry glace"],
["915F6D","Taupe#Mauve taupe|Mauve taupe"],
["918151","Tan (color)#Dark tan|Dark tan"],
["91A3B0","Cadet grey"],
["92000A","Sangria"],
["922724","Auburn hair#Vivid Auburn|Vivid auburn"],
["92A1CF","Variations of blue#Ceil|Ceil"],
["933D41","Topaz|Smokey topaz"],
["9370DB","Purple|Medium purple"],
["93C572","Chartreuse (color)#Pistachio|Pistachio"],
["93CCEA","Cornflower blue#Light cornflower blue|Light cornflower blue"],
["9400D3","Shades of violet#Pigment violet (web color dark violet)|Dark violet"],
["9457EB","Lavender (color)#Lavender indigo|Lavender indigo"],
["9457EB","Lavender (color)#Navy purple|Navy purple"],
["954535","Chestnut (color)|Chestnut"],
["960018","Carmine (color)|Carmine"],
["964B00","Brown|Brown (traditional)"],
["965A3E","List of Crayola crayon colors#Magic Scent|Coconut"],
["966FD6","Purple#Dark pastel purple|Dark pastel purple"],
["967117","Beige#Mode beige|Mode beige"],
["967117","Bistre#Bistre brown|Bistre brown"],
["967117","Desert sand (color)#Sand dune (Drab)|Drab"],
["967117","Desert sand (color)#Sand dune (Drab)|Sand dune"],
["967117","Taupe#Sandy taupe|Sandy taupe"],
["9678B6","Lavender (color)#Lavender purple (purple mountain majesty)|Purple mountain majesty"],
["967BB6","Lavender (color)#Lavender purple (purple mountain majesty)|Lavender purple"],
["96C8A2","Eton blue#Eton blue|Eton blue"],
["96DED1","Robin egg blue#Pale robin egg blue|Pale robin egg blue"],
["979AAA","List of Crayola crayon colors#Standard colors|Manatee"],
["986960","Chestnut (color)#Dark chestnut|Dark chestnut"],
["987456","Liver (color)#Liver (organ)|Liver chestnut"],
["987654","Brown#Pale brown|Pale brown"],
["98777B","Rose (color)#Bazaar|Bazaar"],
["98817B","Cinereous"],
["98FB98","Shades of green#Pale green|Pale green"],
["98FF98","Spring green (color)#Mint green|Mint green"],
["990000","Shades of red#OU Crimson|OU Crimson Red"],
["990000","Shades of red#OU Crimson|Stizza"],
["990000","University of Southern California|USC Cardinal"],
["9932CC","X11 color names#Color names|Dark orchid"],
["9955BB","Lilac (color)#Deep lilac|Deep lilac"],
["996515","Gold (color)#Golden brown|Golden brown"],
["996666","Copper (color)#Copper rose|Copper rose]]|web_safe={{yes"],
["9966CC","Amethyst (color)|Amethyst]]|web_safe={{yes"],
["997A8D","Mountbatten pink"],
["99BADD","Carolina blue"],
["99E6B3","Teal|Teal deer"],
["9AB973","Olive (color)#Olivine|Olivine"],
["9ACD32","Chartreuse (color)#Yellow-green|Yellow-green"],
["9B111E","Ruby (color)#Ruby red|Ruby red"],
["9B7653","List of Crayola crayon colors#Magic Scent|Dirt"],
["9B870C","Yellow#Dark yellow|Dark yellow"],
["9BC4E2","Cerulean#Pale cerulean|Pale cerulean"],
["9BDDFF","Columbia blue"],
["9C2542","Ruby (color)#Big dip o'ruby|Big dip o’ruby"],
["9C7C38","List of Crayola crayon colors#Metallic FX|Metallic Sunburst"],
["9DC209","Chartreuse (color)#Limerick|Limerick"],
["9E1316","Crimson (color)#Spartan Crimson|Spartan Crimson"],
["9EFD38","Lime (color)#French lime|French lime"],
["9F00C5","Purple#Purple (Munsell)|Purple (Munsell)"],
["9F00FF","Shades of violet#Vivid violet|Vivid violet"],
["9F1D35","Burgundy (color)#Vivid burgundy|Vivid burgundy"],
["9F8170","Brown#Beaver|Beaver"],
["9FA91F","Lemon (color)#Citron|Citron"],
["A020F0","Purple#Purple (X11 color) (veronica)|Purple (X11)"],
["A020F0","Purple#Purple (X11 color) (veronica)|Veronica"],
["A0785A","Chamoisee"],
["A0D6B4","Turquoise (color)#Turquoise Green|Turquoise green"],
["A1CAF1","Baby blue#Baby blue eyes|Baby blue eyes"],
["A2006D","Red-violet#Flirt|Flirt"],
["A2A2D0","List of Crayola crayon colors#Standard colors|Blue Bell"],
["A2ADD0","Azure (color)#Wild blue yonder|Wild blue yonder"],
["A32638","Crimson#Alabama Crimson|Alabama Crimson"],
["A3C1AD","Cambridge Blue (colour)|Cambridge Blue"],
["A40000","Candy apple red (color)#Dark candy apple red|Dark candy apple red"],
["A45A52","Redwood (color)|Redwood"],
["A4C639","Android (operating system)#Marketing|Android green"],
["A4DDED","Non-photo blue"],
["A4F4F9","Waterspout"],
["A50B5E","Red-violet#Jazzberry jam|Jazzberry jam"],
["A52A2A","Auburn hair#The color auburn|Auburn"],
["A52A2A","Brown#Red-brown (web color 'brown')|Brown (web)"],
["A52A2A","Brown#Red-brown (web color 'brown')|Red-brown"],
["A57164","Bronze (color)#Blast-off bronze|Blast-off bronze"],
["A67B5B","Beige#French beige|French beige"],
["A67B5B","Coffee (color)#Café au Lait|Café au lait"],
["A67B5B","Tan (color)#Tuscan tan|Tuscan tan"],
["A6E7FF","List of Crayola crayon colors#Magic Scent|Fresh Air"],
["A76BCF","Lavender (color)#Rich Lavender (deep floral lavender)|Rich lavender"],
["A7FC00","Spring bud"],
["A81C07","Rufous"],
["A8516E","Rose (color)#China Rose|China rose"],
["A8E4A0","List of Crayola crayon colors|Granny Smith Apple"],
["A9203E","Carmine (color)#Deep Carmine|Deep carmine"],
["A99A86","Grullo"],
["A9BA9D","Shades of green#Laurel green|Laurel green"],
["AA381E","Vermilion#Chinese red|Chinese red"],
["AA4069","Ruby (color)#Medium ruby|Medium ruby"],
["AA98A9","Rose (color)#Rose Quartz|Rose quartz"],
["AAF0D1","Spring green (color)#Magic mint|Magic mint"],
["AB4B52","Indian red (color)#English red|English red"],
["AB4E52","Rose (color)#Rose Vale|Rose vale"],
["ABCDEF","Pale cornflower blue"],
["AC1E44","Wine (color)#French wine|French wine"],
["ACACAC","Silver (color)#Silver chalice|Silver chalice"],
["ACE1AF","Teal (color)#Celadon|Celadon"],
["ACE5EE","List of Crayola crayon colors#Standard colors|Blizzard Blue"],
["AD6F69","Copper (color)#Copper penny|Copper penny"],
["ADD8E6","Blue#Light blue|Light blue"],
["ADDFAD","Moss green#Light moss green|Light moss green"],
["ADFF2F","Shades of green#Green-yellow|Green-yellow"],
["AE0C00","Mordant red 19"],
["AE2029","Upsdell red"],
["AE6838","Tan (color)#Windsor tan|Windsor tan"],
["AEC6CF","Blue#Pastel blue|Pastel blue"],
["AF4035","Carmine (color)#Medium Carmine|Medium carmine"],
["AF4035","Pale carmine"],
["AFEEEE","Pale blue"],
["AFEEEE","Turquoise (color)#Pale turquoise|Pale turquoise"],
["B03060","Maroon (color)#Rich maroon (maroon (X11))|Rich maroon"],
["B03060","Maroon (color)|Maroon (X11)"],
["B06500","Ginger"],
["B0C4DE","X11 color names#Color name charts|Light steel blue"],
["B0E0E6","Powder blue|Powder blue (web)"],
["B19CD9","Purple#Light pastel purple|Light pastel purple"],
["B22222","X11 color names#Color names|Firebrick"],
["B284BE","Shades of violet#African violet|African violet"],
["B2BEB5","Ash grey"],
["B2EC5D","List of Crayola crayon colors#Standard colors|Inchworm"],
["B2FFFF","Celeste (colour)"],
["B2FFFF","Sky blue#Celeste|Italian sky blue"],
["B31B1B","Carnelian (color)|Carnelian"],
["B31B1B","Shades of red#Cornell Red|Cornell Red"],
["B3446C","Cerise (color)#Irresistible|Irresistible"],
["B3446C","Raspberry (color)#Raspberry rose|Raspberry rose"],
["B38B6D","Taupe#Light taupe|Light taupe"],
["B39EB5","Purple#Pastel purple|Pastel purple"],
["B48395","Lavender (color)#English lavender|English lavender"],
["B53389","Fuchsia (color)#Fandango|Fandango"],
["B5651D","Light brown"],
["B57281","Rose (color)#Turkish Rose|Turkish rose"],
["B57EDC","Lavender (color)#Lavender (floral)|Lavender (floral)"],
["B5A642","Brass"],
["B666D2","Lilac (color)#Rich lilac|Rich lilac"],
["B7410E","Rust (color)|Rust"],
["B768A2","Purple#Pearly purple|Pearly purple"],
["B76E79","Rose (color)#Rose Gold|Rose gold"],
["B784A7","Mauve#Opera mauve|Opera mauve"],
["B78727","Gold (color)#University of California Gold|University of California Gold"],
["B86D29","Liver (color)#Liver (dogs)|Liver (dogs)"],
["B87333","Copper (color)|Copper"],
["B8860B","Goldenrod (color)#Dark goldenrod|Dark goldenrod"],
["B94E48","Chestnut (color)#Deep chestnut|Deep chestnut"],
["B9F2FF","Diamond"],
["BA160C","International orange#International orange (Engineering)|International orange (engineering)"],
["BA55D3","X11 color names#Color names|Medium orchid"],
["BA8759","Deer"],
["BB3385","Red-violet#Medium red-violet|Medium red-violet"],
["BB6528","Ruddy#Ruddy brown|Ruddy brown"],
["BC8F8F","Rose (color)#Rosy Brown|Rosy brown"],
["BC987E","Taupe#Pale taupe (mouse)|Pale taupe"],
["BCD4E6","Aqua_(color)#Pale_aqua|Pale aqua"],
["BCD4E6","Baby blue#Beau blue|Beau blue"],
["BD33A4","Byzantium (color)#Byzantine|Byzantine"],
["BDB76B","Khaki (color)#Dark khaki|Dark khaki"],
["BDDA57","Spring bud#June bud|June bud"],
["BE0032","Crimson#Crimson glory|Crimson glory"],
["BEBEBE","X11 color names#Color names|Gray (X11 gray)"],
["BF00FF","Purple#Electric purple: 2000s|Electric purple"],
["BF4F51","Shades of orange#Bittersweet shimmer|Bittersweet shimmer"],
["BF94E4","Lavender (color)#Bright lavender (light floral lavender) (lavender bandana)|Bright lavender"],
["BFC1C2","Silver (color)#Silver sand|Silver sand"],
["BFFF00","Lime (color)#Bitter lime|Bitter lime"],
["BFFF00","Lime (color)|Lime (color wheel)"],
["C0362C","International orange#International orange (Golden Gate Bridge)|International orange (Golden Gate Bridge)"],
["C04000","Mahogany (color)|Mahogany"],
["C08081","Rose (color)#Old Rose|Old rose"],
["C09999","Tuscan red#Tuscany|Tuscany"],
["C0C0C0","Silver (color)|Silver]]|html_name=Silv"],
["C154C1","Fuchsia (color)#Deep fuchsia|Deep fuchsia"],
["C154C1","Fuchsia (color)#Deep fuchsia|Fuchsia (Crayola)"],
["C19A6B","Brown#Wood brown|Wood brown"],
["C19A6B","Camel (color)#Camel|Camel"],
["C19A6B","Desert sand (color)#Desert|Desert"],
["C19A6B","Fallow (color)|Fallow"],
["C19A6B","Lion (color)|Lion"],
["C21E56","Rose (color)#Rose Red|Rose red"],
["C23B22","Shades of red#Dark pastel red|Dark pastel red"],
["C2B280","Desert sand (color)#Sand|Sand"],
["C2B280","Ecru"],
["C30B4E","Carmine (color)#Pictorial carmine|Pictorial carmine"],
["C32148","Maroon (color)#Bright maroon|Bright maroon"],
["C32148","Maroon (color)#Maroon (Crayola)|Maroon (Crayola)"],
["C3B091","Khaki (color)#Khaki|Khaki (HTML/CSS) (Khaki)"],
["C40233","Shades of red#Red (NCS) (psychological primary red)|Red (NCS)"],
["C41E3A","Cardinal (color)|Cardinal"],
["C46210","Shades of orange#Alloy orange|Alloy orange"],
["C4AEAD","Variations of pink#Silver pink|Silver pink"],
["C4C3D0","Lavender (color)#Lavender gray|Lavender gray"],
["C54B8C","Purple#Mulberry|Mulberry"],
["C5B358","Gold (color)#Vegas gold|Vegas gold"],
["C71585","Red-violet"],
["C71585","Red-violet|Medium violet-red"],
["C72C48","Raspberry (color)#French raspberry|French raspberry"],
["C74375","Rose (color)#Fuchsia Rose|Fuchsia rose"],
["C80815","Venetian red"],
["C84186","Red-violet#Smitten|Smitten"],
["C8A2C8","Lilac (color)|Lilac"],
["C90016","Crimson#Harvard crimson|Harvard crimson"],
["C95A49","List of Crayola crayon colors#Magic Scent|Cedar Chest"],
["C9A0DC","Wisteria (color)|Wisteria"],
["C9C0BB","Silver (color)#Pale silver|Pale silver"],
["C9DC87","Spring bud#Medium spring bud|Medium spring bud"],
["C9FFE5","Cyan#Aero Blue|Aero blue"],
["CA1F7B","Magenta#Historical development of magenta|Magenta (dye)"],
["CA2C92","Fuchsia (color)#Royal fuchsia|Royal fuchsia"],
["CAE00D","Lemon (color)#Bitter lemon|Bitter lemon"],
["CB410B","Sinopia"],
["CB4154","List of Crayola crayon colors#Standard colors|Brick red"],
["CB6D51","Copper (color)#Copper red|Copper red"],
["CB99C9","Violet (color)#Pastel violet|Pastel violet"],
["CBA135","Gold (color)#Satin sheen gold|Satin sheen gold"],
["CC0000","Scarlet (color)#School colors|Boston University Red"],
["CC00CC","Magenta#Deep magenta|Deep magenta"],
["CC00FF","Orchid (color)#Vivid orchid|Vivid orchid"],
["CC3333","Persian red]]|web_safe={{yes"],
["CC3366","Variations of pink#Steel pink|Steel pink"],
["CC4E5C","Terracotta#Color|Dark terra cotta"],
["CC5500","Orange (color)#Burnt orange|Burnt orange"],
["CC6666","List of Crayola crayon colors#Standard colors|Fuzzy Wuzzy"],
["CC7722","Ochre"],
["CC8899","Puce"],
["CCA01D","Lemon (color)#Lemon curry|Lemon curry"],
["CCCCFF","Lavender (color)#Lavender blue|Lavender blue]]|web_safe={{yes"],
["CCCCFF","Periwinkle (color)|Periwinkle]]|web_safe={{yes"],
["CCFF00","Lime (color)#Electric lime|Electric lime]]|web_safe={{yes"],
["CCFF00","List of Crayola colored pencil colors#Twistables|Fluorescent yellow"],
["CD5700","Tenné|Tenné (Tawny)"],
["CD5B45","Coral (color)#Dark coral|Dark coral"],
["CD5C5C","Indian red (color)|Indian red"],
["CD7F32","Bronze (color)|Bronze"],
["CD853F","X11 color names#Color names|Peru"],
["CD9575","List of Crayola crayon colors#Standard colors|Antique brass"],
["CE2029","Fire engine red"],
["CE4676","Ruby (color)#Ruber|Ruber"],
["CEC8EF","List of Crayola crayon colors#Magic Scent|Soap"],
["CF1020","Lava (color)|Lava"],
["CF3476","Variations of magenta#Telemagenta|Telemagenta"],
["CF6BA9","Variations of pink#Super pink|Super pink"],
["CF71AF","Variations of magenta#Sky magenta|Sky magenta"],
["CFB53B","Old gold"],
["CFCFC4","Grey#Pastel gray|Pastel gray"],
["D0417E","Variations of magenta#Magenta (Pantone)|Magenta (Pantone)"],
["D0F0C0","Shades of green#Tea green|Tea green"],
["D10047","Carmine (color)#Spanish carmine|Spanish carmine"],
["D10056","Ruby (color)#Rubine red|Rubine red"],
["D19FE8","Lavender (color)#Bright úbe|Bright ube"],
["D1BEA8","Vanilla (color)#Dark vanilla|Dark vanilla"],
["D1E231","Chartreuse (color)#Pear|Pear"],
["D2691E","Chocolate (color)#Variations of chocolate|Chocolate (web)"],
["D2691E","Chocolate (color)#Variations of chocolate|Cocoa brown"],
["D2691E","Cinnamon"],
["D2B48C","Tan (color)|Tan]]|html_name=T"],
["D3003F","Crimson#Utah crimson|Utah Crimson"],
["D39BCB","Orchid (color)#Light medium orchid|Light medium orchid"],
["D3D3D3","Grey#Web colors|Light gray"],
["D40000","Rosso corsa"],
["D473D4","Mauve#French mauve (deep mauve)|Deep mauve"],
["D473D4","Mauve#French mauve (deep mauve)|French mauve"],
["D4AF37","Gold (color)#Gold (metallic gold)|Gold (metallic)"],
["D6CADD","Lavender (color)#Languid lavender|Languid lavender"],
["D70040","Carmine (color)#Carmine|Carmine (M&P)"],
["D70040","Carmine (color)#Rich Carmine|Rich carmine"],
["D70A53","Debian|Debian red"],
["D71868","Rose (color)#Dogwood Rose|Dogwood rose"],
["D73B3E","Jasper"],
["D77A02","Orchid (color)#Wild orchid|Wild orchid"],
["D7837F","Shades of pink#New York pink|New York pink"],
["D8BFD8","Thistle (color)|Thistle"],
["D9004C","University of Arizona#School colors|UA red"],
["D9603B","Vermilion#Medium vermilion|Medium vermilion"],
["D9603B","Vermilion#Medium vermilion|Vermilion (Plochere)"],
["D98695","List of Crayola crayon colors#Metallic FX|Shimmering Blush"],
["D99058","Persian orange"],
["DA1D81","Cerise (color)#Vivid cerise|Vivid cerise"],
["DA2C43","Shades of red#Rusty red|Rusty red"],
["DA3287","Cerise (color)#Deep cerise|Deep cerise"],
["DA614E","List of Crayola crayon colors#Magic Scent|Jelly Bean"],
["DA70D6","Orchid (colour)|Orchid"],
["DA8A67","Copper (color)#Pale copper|Pale copper"],
["DA8A67","Copper (color)#Variations of copper|Copper (Crayola)"],
["DA9100","Gold (color)#Harvest gold|Harvest gold"],
["DAA520","Goldenrod (color)|Goldenrod"],
["DB7093","Red-violet#Pale red-violet|Pale red-violet"],
["DB7093","Red-violet|Pale violet-red"],
["DBD7D2","List of Crayola crayon colors#Standard colors|Timberwolf"],
["DC143C","Crimson"],
["DCD0FF","Lavender (color)#Pale Lavender|Pale lavender"],
["DCDCDC","X11 color names#Color names identical between X11 and HTML/CSS|Gainsboro"],
["DDA0DD","Lavender (color)#Medium lavender magenta (web color plum)|Medium lavender magenta]]|web_safe={{yes"],
["DDA0DD","Plum (color)#Pale plum|Pale plum]]|web_safe={{yes"],
["DDA0DD","Plum (color)#Pale plum|Plum (web)]]|web_safe={{yes"],
["DDADAF","Pale chestnut"],
["DE3163","Cerise (color)|Cerise"],
["DE3163","Cherry"],
["DE5285","Variations of pink#Fandango pink|Fandango pink"],
["DE5D83","Red-violet#Blush|Blush"],
["DE6FA1","Rose (color)#Thulian Pink|Thulian pink"],
["DE6FA1","Shades of pink#China pink|China pink"],
["DEA5A4","Shades of pink#Pastel pink|Pastel pink"],
["DEAA88","List of Crayola crayon colors|Tumbleweed"],
["DEB887","X11 color names#Color names identical between X11 and HTML/CSS|Burlywood"],
["DF00FF","Purple#Psychedelic purple (phlox)|Phlox"],
["DF00FF","Purple#Psychedelic purple (phlox)|Psychedelic purple"],
["DF73FF","Heliotrope (color)|Heliotrope"],
["DFFF00","Chartreuse (color)|Chartreuse (traditional)"],
["E0115F","Ruby (color)|Ruby"],
["E0218A","Variations of pink#Barbie pink|Barbie pink"],
["E03C31","CG Red"],
["E08D3C","Tiger's eye"],
["E0B0FF","Mauve"],
["E0FFFF","Cyan#Light cyan|Light cyan"],
["E18E96","Ruddy#Ruddy pink|Ruddy pink"],
["E1A95F","Desert sand (color)#Earth yellow|Earth yellow"],
["E1AD21","Urobilin"],
["E2062C","Candy apple red (color)#Medium candy apple red|Medium candy apple red"],
["E25098","Raspberry (color)#Raspberry pink|Raspberry pink"],
["E25822","Flame (color)|Flame"],
["E2725B","Terracotta#Color|Terra cotta"],
["E30022","Cadmium pigments|Cadmium red"],
["E30B5D","Raspberry (color)|Raspberry"],
["E3256B","Rose (color)#Razzmatazz|Razzmatazz"],
["E32636","Alizarin crimson (color)|Alizarin crimson"],
["E32636","Alizarin|Rose madder"],
["E34234","Cinnabar"],
["E34234","Vermilion|Vermilion (cinnabar)"],
["E3A857","Indian yellow"],
["E3AB57","Sunset (color)#Sunray|Sunray"],
["E3DAC9","Shades of white#Bone|Bone"],
["E3F988","Chartreuse (color)#Midori|Midori"],
["E3FF00","Lemon lime"],
["E4007C","Mexican pink"],
["E4717A","Candy apple red (color)#Candy pink|Candy pink"],
["E4717A","Shades of pink#Tango pink|Tango pink"],
["E48400","Fulvous"],
["E49B0F","Gamboge"],
["E4D00A","Citrine (colour)|Citrine"],
["E4D96F","Straw (colour)|Straw"],
["E51A4C","Crimson#Spanish crimson|Spanish crimson"],
["E52B50","Amaranth (color)|Amaranth"],
["E5AA70","Fawn (colour)|Fawn"],
["E5B73B","List of Crayola colored pencil colors#Standard colors|Meat brown"],
["E5CCC9","Variations of gray#Dust storm|Dust storm"],
["E5E4E2","Platinum (color)|Platinum]]|web_safe={{no"],
["E62020","Shades of red#Lust|Lust"],
["E66771","Carmine (color)#Light Carmine Pink|Light carmine pink"],
["E68FAC","Rose (color)#Light Thulian Pink|Light Thulian pink"],
["E68FAC","Shades of pink#Charm pink|Charm pink"],
["E6A8D7","Orchid (color)#Light orchid|Light orchid"],
["E6BE8A","Gold (color)#Pale gold|Pale gold"],
["E6E200","Peridot"],
["E6E6FA","Lavender (color)#Lavender mist|Lavender mist"],
["E6E6FA","Lavender (color)|Lavender (web)"],
["E6E8FA","Glitter"],
["E75480","Pink#Dark pink|Dark pink"],
["E79FC4","Red-violet#Kobi|Kobi"],
["E7ACCF","Pearl|Pink pearl"],
["E7FEFF","Baby blue#Bubbles|Bubbles"],
["E8000D","Crimson#KU Crimson|KU Crimson"],
["E86100","Variations of orange#Spanish orange|Spanish orange"],
["E8CCD7","Variations of pink#Queen pink|Queen pink"],
["E9692C","Shades of orange#Deep carrot orange|Deep carrot orange"],
["E97451","Burnt sienna"],
["E97451","Ochre|Light red ochre"],
["E9967A","Salmon (color)#Dark salmon|Dark salmon"],
["E9D66B","Arylide yellow"],
["E9D66B","Hansa yellow"],
["E9FFDB","Chartreuse (color)#Nyanza|Nyanza"],
["EAE0C8","Pearl (color)|Pearl"],
["EB4C42","Carmine (color)#Carmine Pink|Carmine pink"],
["EC3B83","Cerise (color)#Cerise pink|Cerise pink"],
["EC5800","Shades of orange#Persimmon|Persimmon"],
["ECD540","List of Crayola colored pencil colors#Standard colors|Sandstorm"],
["ECEBBD","Spring bud#Pale spring bud|Pale spring bud"],
["ED1C24","Shades of red#Pigment red|Red (pigment)"],
["ED2939","Shades of red#Imperial red|Imperial red"],
["ED2939","Shades of red#Red (Pantone)|Red (Pantone)"],
["ED872D","Cadmium pigments|Cadmium orange"],
["ED9121","Orange (color)|Carrot orange"],
["EDC9AF","Desert sand (color)|Desert sand"],
["EE204D","Shades of red#Red (Crayola)|Red (Crayola)"],
["EE82EE","Lavender (color)#Lavender magenta (web color 'light violet')|Lavender magenta"],
["EE82EE","Shades of violet#Web color 'violet'|Violet (web)"],
["EED202","Shades of yellow#Safety yellow|Safety yellow"],
["EEDC82","Flax (color)|Flax"],
["EEE600","Titanium yellow"],
["EEE8AA","Goldenrod (color)#Pale goldenrod|Pale goldenrod"],
["EF3038","Carmine (color)#Deep Carmine Pink|Deep carmine pink"],
["EF98AA","List of Crayola crayon colors#Standard colors|Mauvelous"],
["EFBBCC","Shades of pink#Cameo pink|Cameo pink"],
["EFCC00","Shades of yellow#Yellow (Munsell)|Yellow (Munsell)"],
["EFDECD","List of Crayola crayon colors#Standard colors|Almond"],
["F08080","Coral (color)#Light coral|Light coral"],
["F0DC82","Buff (colour)|Buff"],
["F0E130","Dandelion"],
["F0E68C","Khaki (color)#Light khaki|Khaki (X11) (Light khaki)"],
["F0E68C","Khaki (color)#Light khaki|Light khaki"],
["F0EAD6","Eggshell (color)|Eggshell"],
["F0F8FF","Alice blue"],
["F0FFF0","Spring green (color)#Honeydew|Honeydew"],
["F0FFFF","Azure (color)#Azure mist (web color azure)|Azure mist/web"],
["F1A7FE","Lavender (color)#Rich brilliant lavender|Rich brilliant lavender"],
["F2003C","Shades of red#Red (Munsell)|Red (Munsell)"],
["F28500","Tangerine (color)|Tangerine"],
["F28DCD","Orchid (colour)#Orchid pink|Orchid pink"],
["F2F3F4","Anti-flash white"],
["F3D9DF","Vanilla (color)#Vanilla ice|Vanilla ice"],
["F3E5AB","Champagne (color)#Medium champagne|Medium champagne"],
["F3E5AB","Vanilla (color)|Vanilla"],
["F400A1","Cerise (color)#Hollywood cerise|Hollywood cerise"],
["F400A1","Fuchsia (color)#Fashion fuchsia|Fashion fuchsia"],
["F49AC2","Magenta#Pastel magenta|Pastel magenta"],
["F4A460","Sandy brown"],
["F4BBFF","Lavender (color)#Brilliant lavender (electric lavender)|Brilliant lavender"],
["F4BBFF","Lavender (color)#Brilliant lavender (electric lavender)|Electric lavender"],
["F4C2C2","Rose (color)#Tea Rose|Tea rose (rose)"],
["F4C2C2","Shades of pink#Baby pink|Baby pink"],
["F4C430","Saffron (color)|Saffron"],
["F4CA16","Jonquil (color)|Jonquil"],
["F4F0EC","Isabelline (colour)|Isabelline"],
["F56991","Crimson#Light Crimson|Light crimson"],
["F5C71A","Lemon (color)#Deep lemon|Deep lemon"],
["F5DEB3","Wheat (color)|Wheat"],
["F5F5DC","Beige"],
["F5F5F5","Smoke|White smoke"],
["F5FFFA","Spring green (color)#Mint cream|Mint cream"],
["F64A8A","Rose (color)#French Rose|French rose"],
["F6ADC6","Carnation pink#Nadeshiko pink|Nadeshiko pink"],
["F6EABE","Lemon (color)#Lemon meringue|Lemon meringue"],
["F75394","Red-violet#Violet-red|Violet-red"],
["F77F00","University of Tennessee|University of Tennessee Orange"],
["F77FBE","Rose (color)#Persian Pink|Persian pink"],
["F78FA7","List of Crayola crayon colors|Pink Sherbet"],
["F7E7CE","Champagne (color)#Champagne|Champagne"],
["F7E98E","Buff (colour)#Flavescent|Flavescent"],
["F88379","Coral (color)#Coral pink|Coral pink"],
["F88379","Shades of orange#Tea rose|Tea rose (orange)"],
["F88379","Shades of pink#Congo pink|Congo pink"],
["F8B878","Apricot (color)#Mellow apricot|Mellow apricot"],
["F8DE7E","Jasmine (color)|Jasmine"],
["F8DE7E","Shades of yellow#Mellow yellow|Mellow yellow"],
["F8F4FF","Magnolia (color)|Magnolia"],
["F8F8FF","Ghost white"],
["F9429E","Rose (color)#Rose Bonbon|Rose bonbon"],
["F94D00","Shades of orange#Tangelo|Tangelo"],
["F984E5","Variations of magenta#Pale magenta (light fuchsia pink)|Pale magenta"],
["F984EF","Fuchsia (color)#Light fuchsia pink (pale magenta)|Light fuchsia pink"],
["FAD6A5","Beige#Tuscan|Tuscan"],
["FAD6A5","Champagne (color)#Deep champagne|Deep champagne"],
["FAD6A5","Sunset (color)|Sunset"],
["FADA5E","Naples yellow"],
["FADA5E","Shades of yellow#Royal yellow|Royal yellow"],
["FADA5E","Stil de grain yellow"],
["FADADD","Shades of pink#Pale pink|Pale pink"],
["FADFAD","Peach (color)#Peach-yellow|Peach-yellow"],
["FAE7B5","List of Crayola crayon colors#Standard colors|Banana Mania"],
["FAEBD7","Moccasin"],
["FAEBD7","Shades of white#Antique white|Antique white"],
["FAF0BE","Blond"],
["FAF0E6","Linen (color)|Linen"],
["FAFAD2","Goldenrod (color)#Light goldenrod yellow|Light goldenrod yellow"],
["FB4F14","Shades of orange|Orioles orange"],
["FB607F","Rose (color)#Brink Pink|Brink pink"],
["FB9902","RYB color model|Orange (RYB)"],
["FBA0E3","Lavender (color)#Lavender rose|Lavender rose"],
["FBAB60","Saffron (color)#Rajah|Rajah"],
["FBAED2","Lavender (color)#Lavender pink|Lavender pink"],
["FBCCE7","Rose (color)#Classic Rose|Classic rose"],
["FBCEB1","Apricot (color)|Apricot"],
["FBEC5D","Corn (color)|Corn"],
["FBEC5D","Maize (color)|Maize"],
["FC0FC0","Shades of pink#Shocking pink|Shocking pink"],
["FC5A8D","List of Crayola crayon colors#Magic Scent|Strawberry"],
["FC6C85","List of Crayola crayon colors#Standard colors|Wild Watermelon"],
["FC89AC","Rose (color)#Tickle Me Pink|Tickle Me Pink"],
["FC8EAC","Flamingo|Flamingo pink"],
["FCC200","Gold (color)#Golden poppy|Golden poppy"],
["FCE883","Shades of yellow#Yellow (Crayola)|Yellow (Crayola)"],
["FCF75E","Icterine"],
["FD0E35","Scarlet (color)#Scarlet (Crayola)|Scarlet (Crayola)"],
["FD0E35","Scarlet (color)#Tractor red|Tractor red"],
["FD5E53","Sunset (color)#Sunset orange|Sunset orange"],
["FDBCB4","Variations of orange#Melon|Melon"],
["FDD5B1","Apricot (color)#Light apricot|Light apricot"],
["FDD5B1","Feldspar"],
["FDDDE6","Pig|Piggy pink"],
["FDEE00","Aureolin"],
["FDF5E6","Old lace (color)|Old lace"],
["FDFD96","Shades of yellow#Pastel yellow|Pastel yellow"],
["FDFF00","Lemon (color)#Lemon glacier|Lemon glacier"],
["FE2712","RYB color model|Red (RYB)]]|web_safe={{yes"],
["FE28A2","Rose (color)#Persian Rose|Persian rose"],
["FE4164","Fuchsia (color)#Neon fuchsia|Neon fuchsia"],
["FE4EDA","Variations of magenta#Purple pizzazz|Purple pizzazz"],
["FE5A1D","Shades of orange#Giants orange|Giants orange"],
["FE6F5E","Shades of orange#Bittersweet|Bittersweet"],
["FEDF00","Shades of yellow#Yellow (Pantone)|Yellow (Pantone)"],
["FEFE33","RYB color model|Yellow (RYB)"],
["FEFEFA","Shades of white#Baby powder|Baby powder"],
["FF0000","Red]]|html_name=Red|web_safe={{yes"],
["FF0028","Ruddy"],
["FF0038","Carmine (color)#Carmine Red|Carmine red"],
["FF003F","Crimson#Electric crimson|Electric crimson"],
["FF004F","Crimson#Folly|Folly"],
["FF007F","Rose (color)|Rose"],
["FF007F","Shades of pink#Bright pink|Bright pink"],
["FF0090","Magenta#Historical development of magenta|Magenta (process)"],
["FF00FF","Fuchsia (color)|Fuchsia]]|html_name=Fuchsia|web_safe={{yes"],
["FF00FF","Magenta]]|html_name=Fuchsia|web_safe={{yes"],
["FF033E","Rose (color)#American Rose|American rose"],
["FF0800","Candy apple red (color)|Candy apple red"],
["FF1493","List of Crayola colored pencil colors#Twistables|Fluorescent pink"],
["FF1493","Shades of pink#Deep pink|Deep pink"],
["FF1DCE","Variations of magenta#Hot magenta|Hot magenta"],
["FF2400","Scarlet (color)|Scarlet"],
["FF2800","Ferrari|Ferrari Red"],
["FF33CC","Rose (color)#Razzle Dazzle Rose|Razzle dazzle rose"],
["FF355E","Amaranth (color)#Radical red (bright amaranth pink)|Radical Red"],
["FF3800","Coquelicot"],
["FF4040","Coral (color)#Coral red|Coral red"],
["FF43A4","List of Crayola crayon colors#Standard colors|Wild Strawberry"],
["FF4500","Vermilion#Orange-red|Orange-red"],
["FF4F00","International orange|International orange (aerospace)"],
["FF5349","Vermilion#Red-orange|Red-orange"],
["FF55A3","Rose (color)#Brilliant Rose|Brilliant rose"],
["FF55A3","Variations of magenta#Magenta (Crayola)|Magenta (Crayola)"],
["FF5800","Shades of orange#Orange (Pantone)|Orange (Pantone)"],
["FF5A36","Portland Orange"],
["FF6347","Tomato (color)|Tomato"],
["FF66CC","Rose (color)#Rose Pink|Rose pink"],
["FF6700","Safety orange|Safety orange (blaze orange)]]|web_safe={{yes"],
["FF6961","Shades of red#Pastel red|Pastel red"],
["FF69B4","Shades of pink#Hot pink|Hot pink"],
["FF6E4A","List of Crayola crayon colors#Standard colors|Outrageous Orange"],
["FF6FFF","Variations of magenta#Ultra pink|Shocking pink (Crayola)"],
["FF6FFF","Variations of magenta#Ultra pink|Ultra pink"],
["FF7518","Pumpkin (color)|Pumpkin"],
["FF7538","Shades of orange#Orange (Crayola)|Orange (Crayola)"],
["FF77FF","Fuchsia (color)#Fuchsia pink (light magenta)|Fuchsia pink"],
["FF7E00","Amber (color)|SAE/ECE Amber (color)"],
["FF7F00","Shades of orange#Orange (color wheel)|Orange (color wheel)"],
["FF7F50","Coral (color)|Coral"],
["FF8243","List of Crayola crayon colors#Standard colors|Mango Tango"],
["FF878D","List of Crayola crayon colors#Magic Scent|Tulip"],
["FF8C00","Shades of orange#Dark orange (web color)|Dark orange"],
["FF8C69","Salmon (color)|Salmon"],
["FF8F00","Shades of orange#Princeton orange|Princeton orange"],
["FF91A4","Salmon pink"],
["FF91AF","Baker-Miller Pink|Baker-Miller pink"],
["FF91AF","Baker-Miller Pink|Schauss pink"],
["FF9933","Saffron (color)#Deep saffron|Deep saffron"],
["FF9966","Shades of orange#Atomic tangerine|Atomic tangerine"],
["FF9966","nk-orange|web_safe={{yes"],
["FF9999","Salmon pink#Light salmon pink|Light salmon pink"],
["FF9F00","Shades of orange#Orange peel|Orange peel"],
["FFA07A","Salmon (color)#Light salmon|Light salmon"],
["FFA089","List of Crayola crayon colors#Standard colors|Vivid tangerine"],
["FFA343","List of Crayola crayon colors#Standard colors|Neon Carrot"],
["FFA500","Shades of orange#Orange (web color)|Orange (web color)"],
["FFA6C9","Carnation pink"],
["FFA700","Chrome yellow"],
["FFA812","Shades of orange#Dark tangerine|Dark tangerine"],
["FFAE42","List of Crayola crayon colors#Standard colors|Yellow Orange"],
["FFB300","UCLA|UCLA Gold"],
["FFB347","Orange (colour)#Pastel orange|Pastel orange"],
["FFB6C1","Pink#Light pink|Light pink"],
["FFB7C5","Shades of pink#Cherry blossom pink|Cherry blossom pink"],
["FFBA00","Selective yellow"],
["FFBCD9","Cotton candy"],
["FFBF00","Amber (color)|Amber"],
["FFBF00","List of Crayola colored pencil colors#Twistables|Fluorescent orange"],
["FFC0CB","Pink"],
["FFC1CC","List of Crayola colored pencil colors#Standard colors|Bubble gum"],
["FFC40C","Mikado yellow"],
["FFC87C","Topaz"],
["FFCBA4","Peach (color)#(Crayola)|Peach (Crayola)"],
["FFCBA4","Peach (color)#Deep peach|Deep peach"],
["FFCC00","School bus yellow#Computer monitor display|Tangerine yellow]]|web_safe={{yes"],
["FFCC00","University of Southern California|USC Gold"],
["FFCC33","Sunset (color)#Sunglow|Sunglow"],
["FFCC99","Peach (color)#Peach-orange|Peach-orange]]|web_safe={{yes"],
["FFCFF1","List of Crayola crayon colors#Magic Scent|Shampoo"],
["FFD300","Shades of yellow#Cyber yellow|Cyber yellow"],
["FFD300","Shades of yellow#Yellow (NCS) (psychological primary yellow)|Yellow (NCS)"],
["FFD700","Gold (color)|Gold (web) (Golden)]]|html_name=Go"],
["FFD800","School bus yellow"],
["FFDAB9","Peach (color)#Peach puff|Peach puff"],
["FFDB58","Mustard (color)|Mustard"],
["FFDDCA","Beige#Unbleached silk|Unbleached silk"],
["FFDDF4","Shades of pink#Pink lace|Pink lace"],
["FFDEAD","Navajo white"],
["FFDF00","Gold (color)#Golden yellow|Golden yellow"],
["FFE135","Banana|Banana yellow"],
["FFE4C4","X11 color names#Color names|Bisque"],
["FFE4CD","List of Crayola crayon colors#Magic Scent|Lumber"],
["FFE4E1","Rose (color)#Misty Rose|Misty rose"],
["FFE5B4","Peach (color)|Peach"],
["FFEBCD","X11 color names|Blanched almond"],
["FFEF00","Yellow#Electric yellow vs. process yellow|Canary yellow"],
["FFEF00","Yellow#Electric yellow vs. process yellow|Yellow (process)"],
["FFEFD5","Shades of orange#Papaya whip|Papaya whip"],
["FFF000","Shades of yellow|Yellow rose"],
["FFF0F5","Lavender (color)#Lavender blush|Lavender blush"],
["FFF44F","Lemon (color)#Lemon yellow|Lemon yellow"],
["FFF5EE","Seashell (color)|Seashell"],
["FFF600","Cadmium pigments|Cadmium yellow"],
["FFF700","Lemon (color)|Lemon"],
["FFF8DC","Shades of white#Cornsilk|Cornsilk"],
["FFF8E7","Cosmic latte"],
["FFFACD","Lemon chiffon"],
["FFFAF0","X11 color names#Color names|Floral white"],
["FFFAFA","Shades of white#Snow|Snow"],
["FFFDD0","Cream (colour)|Cream"],
["FFFF00","Yellow]]|html_name=Yellow|web_safe={{yes"],
["FFFF31","Daffodil"],
["FFFF33","Yellow|Electric yellow"],
["FFFF66","Lemon (color)#Laser lemon|Laser Lemon"],
["FFFF66","Shades of yellow#Unmellow yellow|Unmellow yellow"],
["FFFFE0","Shades of yellow#Light yellow|Light yellow"],
["FFFFF0","Ivory (color)|Ivory]]|web_safe={{yes"],
["FFFFFF","White]]|html_name=White|web_safe={{yes"]
]

}

ntc.init();